// AUTO-GENERATED by packages/illustrations/build.mjs — DO NOT EDIT BY HAND.
// Source: packages/illustrations/svg/ or raster-src/. Run `npm run illustrations:build`.

import * as React from 'react';

const _svg = "<svg viewBox=\"0 0 22 22\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\" width=\"100%\" height=\"100%\">\n<path d=\"M10.75 0C16.6871 0 21.5 4.81294 21.5 10.75C21.5 16.6871 16.6871 21.5 10.75 21.5C4.81294 21.5 0 16.6871 0 10.75C0 4.81294 4.81294 0 10.75 0ZM10.75 1.5C5.64137 1.5 1.5 5.64137 1.5 10.75C1.5 15.8586 5.64137 20 10.75 20C15.8586 20 20 15.8586 20 10.75C20 5.64137 15.8586 1.5 10.75 1.5ZM11.0273 4.5C11.4414 4.50023 11.7773 4.83593 11.7773 5.25V6.38086H12.4346C13.9106 6.38088 15.0654 7.67512 15.0654 9.01172C15.0654 9.56882 14.8903 10.0844 14.5947 10.5098C15.4156 10.9555 16 11.7625 16 12.7617C15.9999 14.3035 14.6109 15.3926 13.1035 15.3926H11.7773V16.5117C11.7773 16.9257 11.4413 17.2615 11.0273 17.2617C10.6132 17.2617 10.2774 16.9259 10.2773 16.5117V15.3926H9.43457V16.5117C9.4345 16.9259 9.09874 17.2617 8.68457 17.2617C8.27042 17.2617 7.93464 16.9259 7.93457 16.5117V15.3926H7.75C7.70669 15.3926 7.66435 15.3879 7.62305 15.3809H6.25C5.8358 15.3809 5.50002 15.0451 5.5 14.6309C5.5 14.2166 5.83579 13.8809 6.25 13.8809H7V7.88086H6.25C5.83581 7.88086 5.50004 7.54504 5.5 7.13086C5.5 6.71665 5.83579 6.38086 6.25 6.38086H7.93457V5.25C7.93457 4.8358 8.27037 4.50002 8.68457 4.5C9.09878 4.5 9.43457 4.83579 9.43457 5.25V6.38086H10.2773V5.25C10.2773 4.83579 10.6131 4.5 11.0273 4.5ZM12.4346 11.6426H8.5V13.8809H9.52734C9.57034 13.8809 9.6123 13.8856 9.65332 13.8926H10.9004C10.9416 13.8856 10.9842 13.8809 11.0273 13.8809C11.0703 13.8809 11.1123 13.8856 11.1533 13.8926H13.1035C13.9729 13.8926 14.4999 13.2967 14.5 12.7617C14.5 12.2267 13.973 11.6309 13.1035 11.6309H12.665C12.589 11.6375 12.5123 11.6426 12.4346 11.6426ZM8.5 10.1309H12.5869C13.139 10.0563 13.5654 9.58416 13.5654 9.01172C13.5654 8.45602 13.0354 7.88088 12.4346 7.88086H8.5V10.1309Z\" fill=\"#121212\"/>\n</svg>\n";

export interface CoinProps {
  /** Rendered width. Height is calculated automatically (intrinsic ratio 240∶180). */
  width?: number | string;
  /** Accessible label. Omit for purely decorative illustrations. */
  alt?: string;
  className?: string;
  style?: React.CSSProperties;
}

export function Coin({ width = 240, alt, className, style }: CoinProps) {
  return (
    <span
      role={alt ? 'img' : 'presentation'}
      aria-label={alt}
      aria-hidden={!alt}
      className={className}
      style={{ display: 'inline-block', width, aspectRatio: '240/180', overflow: 'hidden', flexShrink: 0, ...style }}
      // eslint-disable-next-line react/no-danger
      dangerouslySetInnerHTML={{ __html: _svg }}
    />
  );
}
