// AUTO-GENERATED by packages/illustrations/build.mjs — DO NOT EDIT BY HAND.
// Source: packages/illustrations/svg/ or raster-src/. Run `npm run illustrations:build`.

import * as React from 'react';

const _svg = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 240 180\" fill=\"none\" width=\"100%\" height=\"100%\">\n  <rect width=\"240\" height=\"180\" rx=\"16\" fill=\"#EFF6FF\"/>\n  <rect x=\"60\" y=\"80\" width=\"120\" height=\"76\" rx=\"8\" fill=\"#FFFFFF\"/>\n  <rect x=\"60\" y=\"80\" width=\"120\" height=\"76\" rx=\"8\" stroke=\"#BFDBFE\" stroke-width=\"2\"/>\n  <path d=\"M60 88H108C110.209 88 112 86.209 112 84V80H60V88Z\" fill=\"#DBEAFE\"/>\n  <rect x=\"76\" y=\"104\" width=\"88\" height=\"8\" rx=\"4\" fill=\"#BFDBFE\"/>\n  <rect x=\"76\" y=\"120\" width=\"64\" height=\"8\" rx=\"4\" fill=\"#BFDBFE\"/>\n  <rect x=\"76\" y=\"136\" width=\"40\" height=\"8\" rx=\"4\" fill=\"#EFF6FF\" stroke=\"#BFDBFE\" stroke-width=\"1\"/>\n  <circle cx=\"120\" cy=\"50\" r=\"22\" fill=\"#3B82F6\"/>\n  <path d=\"M120 40V60M110 50H130\" stroke=\"#FFFFFF\" stroke-width=\"3\" stroke-linecap=\"round\"/>\n</svg>\n";

export interface EmptyStateProps {
  /** Rendered width. Height is calculated automatically (intrinsic ratio 240∶180). */
  width?: number | string;
  /** Accessible label. Omit for purely decorative illustrations. */
  alt?: string;
  className?: string;
  style?: React.CSSProperties;
}

export function EmptyState({ width = 240, alt, className, style }: EmptyStateProps) {
  return (
    <span
      role={alt ? 'img' : 'presentation'}
      aria-label={alt}
      aria-hidden={!alt}
      className={className}
      style={{ display: 'inline-block', width, aspectRatio: '240/180', overflow: 'hidden', flexShrink: 0, ...style }}
      // eslint-disable-next-line react/no-danger
      dangerouslySetInnerHTML={{ __html: _svg }}
    />
  );
}
