// AUTO-GENERATED by packages/illustrations/build.mjs — DO NOT EDIT BY HAND.
// Source: packages/illustrations/svg/ or raster-src/. Run `npm run illustrations:build`.

import * as React from 'react';

// Resolved by the consuming app's bundler (webpack / Vite / Metro).
// Add `declare module '*.webp' { const src: string; export default src; }`
// to your tsconfig if you see a TypeScript module-not-found error.
// eslint-disable-next-line @typescript-eslint/no-require-imports
const _src   = require('../../raster/hero-banner.webp') as string;
// eslint-disable-next-line @typescript-eslint/no-require-imports
const _src2x = require('../../raster/hero-banner@2x.webp') as string;

export interface HeroBannerProps {
  /** Rendered width. Height auto-calculated (intrinsic 200∶150). */
  width?: number | string;
  alt?: string;
  className?: string;
  style?: React.CSSProperties;
}

export function HeroBanner({ width = 200, alt = '', className, style }: HeroBannerProps) {
  return (
    <img
      src={_src}
      srcSet={`${_src} 1x, ${_src2x} 2x`}
      width={width}
      height={Math.round(Number(width) * 150 / 200)}
      alt={alt}
      className={className}
      style={{ aspectRatio: '200/150', ...style }}
    />
  );
}
