// AUTO-GENERATED by packages/illustrations/build.mjs — DO NOT EDIT BY HAND.
// Source: packages/illustrations/svg/ or raster-src/. Run `npm run illustrations:build`.

import * as React from 'react';
import { Coin } from './Coin';
import { Battery } from './Battery';
import type { IllustrationMeta } from '../../manifest';

type IllustrationName = 'coin' | 'battery';

const REGISTRY: Record<string, React.ComponentType<{ width?: number | string; alt?: string; className?: string; style?: React.CSSProperties }>> = {
  'coin': Coin,
  'battery': Battery,
};

export interface IllustrationProps {
  /** Illustration identifier. */
  name: IllustrationName;
  /** Width override. Defaults to the intrinsic 1× width. */
  width?: number | string;
  /** Accessible label. Omit for decorative illustrations. */
  alt?: string;
  className?: string;
  style?: React.CSSProperties;
}

export function Illustration({ name, width, alt, className, style }: IllustrationProps) {
  const Component = REGISTRY[name];
  if (!Component) {
    if (process.env.NODE_ENV !== 'production') {
      // eslint-disable-next-line no-console
      console.warn('[Illustration] Unknown name:', name);
    }
    return null;
  }
  return <Component width={width} alt={alt} className={className} style={style} />;
}
