// AUTO-GENERATED by packages/icons/build.mjs — DO NOT EDIT BY HAND.
// Source: packages/icons/svg/. Run `npm run icons:build` to regenerate.

import * as React from 'react';
import Svg, { Path } from 'react-native-svg';

export interface AngleSmallUpProps {
  size?: number;
  color?: string;
}

export function AngleSmallUp({ size = 24, color = 'currentColor' }: AngleSmallUpProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none">
      <Path d="M17.2933 15.207L12.0003 9.91399L6.70733 15.207L5.29333 13.793L10.5863 8.49999C10.9614 8.12504 11.47 7.91441 12.0003 7.91441C12.5307 7.91441 13.0393 8.12504 13.4143 8.49999L18.7073 13.793L17.2933 15.207Z" fill={color}/>
    </Svg>
  );
}
