// AUTO-GENERATED by packages/icons/build.mjs — DO NOT EDIT BY HAND.
// Source: packages/icons/svg/. Run `npm run icons:build` to regenerate.

import * as React from 'react';
import Svg, { Path } from 'react-native-svg';

export interface AngleSmallRightProps {
  size?: number;
  color?: string;
}

export function AngleSmallRight({ size = 24, color = 'currentColor' }: AngleSmallRightProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none">
      <Path d="M10.8111 18.707L9.40012 17.293L14.6891 12L9.40012 6.70698L10.8151 5.29298L16.1001 10.586C16.475 10.961 16.6857 11.4697 16.6857 12C16.6857 12.5303 16.475 13.0389 16.1001 13.414L10.8111 18.707Z" fill={color}/>
    </Svg>
  );
}
