// AUTO-GENERATED by packages/icons/build.mjs — DO NOT EDIT BY HAND.
// Source: packages/icons/svg/. Run `npm run icons:build` to regenerate.

import * as React from 'react';
import Svg, { Path } from 'react-native-svg';

export interface ArrowSmallLeftProps {
  size?: number;
  color?: string;
}

export function ArrowSmallLeft({ size = 24, color = 'currentColor' }: ArrowSmallLeftProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none">
      <Path d="M18.9998 10.9999H8.99984L12.2928 7.70694L10.8788 6.29294L6.58584 10.5859C6.2109 10.961 6.00027 11.4696 6.00027 11.9999C6.00027 12.5303 6.2109 13.0389 6.58584 13.4139L10.8788 17.7069L12.2928 16.2929L8.99984 12.9999H18.9998V10.9999Z" fill={color}/>
    </Svg>
  );
}
