// AUTO-GENERATED by packages/icons/build.mjs — DO NOT EDIT BY HAND.
// Source: packages/icons/svg/. Run `npm run icons:build` to regenerate.

import * as React from 'react';
import Svg, { Path } from 'react-native-svg';

export interface CloseProps {
  size?: number;
  color?: string;
}

export function Close({ size = 24, color = 'currentColor' }: CloseProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none">
      <Path d="M18 6L6 18M6 6L18 18" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
    </Svg>
  );
}
