// AUTO-GENERATED by packages/icons/build.mjs — DO NOT EDIT BY HAND.
// Source: packages/icons/svg/. Run `npm run icons:build` to regenerate.

import * as React from 'react';

export interface AngleSmallLeftProps extends React.SVGProps<SVGSVGElement> {
  size?: number | string;
  color?: string;
}

export const AngleSmallLeft = React.forwardRef<SVGSVGElement, AngleSmallLeftProps>(
  function AngleSmallLeft({ size = 24, color = 'currentColor', ...rest }, ref) {
    return (
      <svg
        ref={ref}
        xmlns="http://www.w3.org/2000/svg"
        width={size}
        height={size}
        viewBox="0 0 24 24"
        fill="none"
        aria-hidden="true"
        {...rest}
      >
        <path d="M13.7751 18.707L8.48207 13.414C8.10713 13.0389 7.8965 12.5303 7.8965 12C7.8965 11.4697 8.10713 10.961 8.48207 10.586L13.7751 5.29298L15.1891 6.70698L9.90007 12L15.1931 17.293L13.7751 18.707Z" fill={color}/>
      </svg>
    );
  }
);

AngleSmallLeft.displayName = 'AngleSmallLeft';
