// AUTO-GENERATED by packages/icons/build.mjs — DO NOT EDIT BY HAND.
// Source: packages/icons/svg/. Run `npm run icons:build` to regenerate.

import * as React from 'react';

export interface AngleSmallDownProps extends React.SVGProps<SVGSVGElement> {
  size?: number | string;
  color?: string;
}

export const AngleSmallDown = React.forwardRef<SVGSVGElement, AngleSmallDownProps>(
  function AngleSmallDown({ size = 24, color = 'currentColor', ...rest }, ref) {
    return (
      <svg
        ref={ref}
        xmlns="http://www.w3.org/2000/svg"
        width={size}
        height={size}
        viewBox="0 0 24 24"
        fill="none"
        aria-hidden="true"
        {...rest}
      >
        <path d="M11.9999 15.5C11.7373 15.5005 11.4771 15.449 11.2345 15.3486C10.9918 15.2482 10.7714 15.1009 10.5859 14.915L5.29286 9.62102L6.70686 8.20702L11.9999 13.5L17.2929 8.20702L18.7069 9.62102L13.4139 14.914C13.2284 15.1001 13.008 15.2476 12.7654 15.3482C12.5227 15.4487 12.2625 15.5003 11.9999 15.5Z" fill={color}/>
      </svg>
    );
  }
);

AngleSmallDown.displayName = 'AngleSmallDown';
