// AUTO-GENERATED by packages/icons/build.mjs — DO NOT EDIT BY HAND.
// Source: packages/icons/svg/. Run `npm run icons:build` to regenerate.

export { AngleSmallDown } from './AngleSmallDown';
export type { AngleSmallDownProps } from './AngleSmallDown';
export { AngleSmallLeft } from './AngleSmallLeft';
export type { AngleSmallLeftProps } from './AngleSmallLeft';
export { AngleSmallRight } from './AngleSmallRight';
export type { AngleSmallRightProps } from './AngleSmallRight';
export { AngleSmallUp } from './AngleSmallUp';
export type { AngleSmallUpProps } from './AngleSmallUp';
export { ArrowSmallLeft } from './ArrowSmallLeft';
export type { ArrowSmallLeftProps } from './ArrowSmallLeft';
export { ArrowSmallRight } from './ArrowSmallRight';
export type { ArrowSmallRightProps } from './ArrowSmallRight';

export type IconName = 'angle-small-down' | 'angle-small-left' | 'angle-small-right' | 'angle-small-up' | 'arrow-small-left' | 'arrow-small-right';
