// AUTO-GENERATED by packages/icons/build.mjs — DO NOT EDIT BY HAND.
// Source: packages/icons/svg/. Run `npm run icons:build` to regenerate.

import * as React from 'react';

export interface SearchProps extends React.SVGProps<SVGSVGElement> {
  size?: number | string;
  color?: string;
}

export const Search = React.forwardRef<SVGSVGElement, SearchProps>(
  function Search({ size = 24, color = 'currentColor', ...rest }, ref) {
    return (
      <svg
        ref={ref}
        xmlns="http://www.w3.org/2000/svg"
        width={size}
        height={size}
        viewBox="0 0 24 24"
        fill="none"
        aria-hidden="true"
        {...rest}
      >
        <circle cx="11" cy="11" r="8" stroke={color} strokeWidth="2"/>
        <path d="M21 21L16.65 16.65" stroke={color} strokeWidth="2" strokeLinecap="round"/>
      </svg>
    );
  }
);

Search.displayName = 'Search';
