// AUTO-GENERATED by packages/illustrations/build.mjs — DO NOT EDIT BY HAND.
// Source: packages/illustrations/svg/ or raster-src/. Run `npm run illustrations:build`.

import * as React from 'react';
import { Image } from 'react-native';

// eslint-disable-next-line @typescript-eslint/no-require-imports
const _source = require('../../raster/battery.webp') as number;

export interface BatteryProps {
  /** Rendered width in dp. Height auto-calculated (intrinsic 188∶98). */
  width?: number;
  accessibilityLabel?: string;
}

export function Battery({ width = 188, accessibilityLabel }: BatteryProps) {
  const height = Math.round(width * 98 / 188);
  return (
    <Image
      source={_source}
      style={{ width, height }}
      accessible={!!accessibilityLabel}
      accessibilityLabel={accessibilityLabel}
      resizeMode="contain"
    />
  );
}
