// AUTO-GENERATED by packages/illustrations/build.mjs — DO NOT EDIT BY HAND.
// Source: packages/illustrations/svg/ or raster-src/. Run `npm run illustrations:build`.

import * as React from 'react';
import { SvgXml } from 'react-native-svg';

const _svgXml = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 240 180\" fill=\"none\" width=\"100%\" height=\"100%\">\n  <rect width=\"240\" height=\"180\" rx=\"16\" fill=\"#EFF6FF\"/>\n  <rect x=\"60\" y=\"80\" width=\"120\" height=\"76\" rx=\"8\" fill=\"#FFFFFF\"/>\n  <rect x=\"60\" y=\"80\" width=\"120\" height=\"76\" rx=\"8\" stroke=\"#BFDBFE\" stroke-width=\"2\"/>\n  <path d=\"M60 88H108C110.209 88 112 86.209 112 84V80H60V88Z\" fill=\"#DBEAFE\"/>\n  <rect x=\"76\" y=\"104\" width=\"88\" height=\"8\" rx=\"4\" fill=\"#BFDBFE\"/>\n  <rect x=\"76\" y=\"120\" width=\"64\" height=\"8\" rx=\"4\" fill=\"#BFDBFE\"/>\n  <rect x=\"76\" y=\"136\" width=\"40\" height=\"8\" rx=\"4\" fill=\"#EFF6FF\" stroke=\"#BFDBFE\" stroke-width=\"1\"/>\n  <circle cx=\"120\" cy=\"50\" r=\"22\" fill=\"#3B82F6\"/>\n  <path d=\"M120 40V60M110 50H130\" stroke=\"#FFFFFF\" stroke-width=\"3\" stroke-linecap=\"round\"/>\n</svg>\n";
const _aspect = 180 / 240;

export interface EmptyStateProps {
  /** Rendered width in dp. Height derived from intrinsic ratio (240∶180). */
  width?: number;
  accessibilityLabel?: string;
}

export function EmptyState({ width = 240, accessibilityLabel }: EmptyStateProps) {
  const height = Math.round(width * _aspect);
  return (
    <SvgXml
      xml={_svgXml}
      width={width}
      height={height}
      accessible={!!accessibilityLabel}
      accessibilityLabel={accessibilityLabel}
    />
  );
}
