// AUTO-GENERATED by packages/illustrations/build.mjs — DO NOT EDIT BY HAND.
// Source: packages/illustrations/svg/ or raster-src/. Run `npm run illustrations:build`.

import * as React from 'react';
import { Image } from 'react-native';

// eslint-disable-next-line @typescript-eslint/no-require-imports
const _source = require('../../raster/error.webp') as number;

export interface ErrorProps {
  /** Rendered width in dp. Height auto-calculated (intrinsic 54∶54). */
  width?: number;
  accessibilityLabel?: string;
}

export function Error({ width = 54, accessibilityLabel }: ErrorProps) {
  const height = Math.round(width * 54 / 54);
  return (
    <Image
      source={_source}
      style={{ width, height }}
      accessible={!!accessibilityLabel}
      accessibilityLabel={accessibilityLabel}
      resizeMode="contain"
    />
  );
}
