// AUTO-GENERATED by packages/illustrations/build.mjs — DO NOT EDIT BY HAND.
// Source: packages/illustrations/svg/ or raster-src/. Run `npm run illustrations:build`.

import * as React from 'react';
import { Image } from 'react-native';

// eslint-disable-next-line @typescript-eslint/no-require-imports
const _source = require('../../raster/hero-banner.webp') as number;

export interface HeroBannerProps {
  /** Rendered width in dp. Height auto-calculated (intrinsic 200∶150). */
  width?: number;
  accessibilityLabel?: string;
}

export function HeroBanner({ width = 200, accessibilityLabel }: HeroBannerProps) {
  const height = Math.round(width * 150 / 200);
  return (
    <Image
      source={_source}
      style={{ width, height }}
      accessible={!!accessibilityLabel}
      accessibilityLabel={accessibilityLabel}
      resizeMode="contain"
    />
  );
}
