// AUTO-GENERATED by packages/illustrations/build.mjs — DO NOT EDIT BY HAND.
// Source: packages/illustrations/svg/ or raster-src/. Run `npm run illustrations:build`.

import * as React from 'react';
import { EmptyState } from './EmptyState';
import { HeroBanner } from './HeroBanner';

type IllustrationName = 'empty-state' | 'hero-banner';

const REGISTRY: Record<string, React.ComponentType<{ width?: number; accessibilityLabel?: string }>> = {
  'empty-state': EmptyState,
  'hero-banner': HeroBanner,
};

export interface IllustrationProps {
  name: IllustrationName;
  width?: number;
  accessibilityLabel?: string;
}

export function Illustration({ name, width, accessibilityLabel }: IllustrationProps) {
  const Component = REGISTRY[name];
  if (!Component) return null;
  return <Component width={width} accessibilityLabel={accessibilityLabel} />;
}
