// AUTO-GENERATED by packages/illustrations/build.mjs — DO NOT EDIT BY HAND.
// Source: packages/illustrations/svg/ or raster-src/. Run `npm run illustrations:build`.

export { Coin } from './Coin';
export type { CoinProps } from './Coin';
export { Battery } from './Battery';
export type { BatteryProps } from './Battery';
export { Error } from './Error';
export type { ErrorProps } from './Error';
export { Illustration } from './Illustration';
export type { IllustrationProps } from './Illustration';
