// AUTO-GENERATED by packages/tokens/build.mjs — DO NOT EDIT BY HAND.
// Resolved token theme objects for React Native / non-CSS consumers.
// RN can't read CSS variables, so every value is fully resolved per theme.
// Includes text.mobile.* typography roles (not text.web.*).

export type ThemeName = "light" | "dark";

export const themes = {
  light: {
  "color": {
    "neutral": {
      "50": "#F8F9FA",
      "100": "#F0F2F4",
      "200": "#E6E8EB",
      "300": "#D7DBDF",
      "400": "#C1C8CD",
      "500": "#889096",
      "600": "#697177",
      "700": "#4D5358",
      "800": "#2C3338",
      "900": "#1A1F23",
      "950": "#11181C"
    },
    "brand": {
      "50": "#EEF2FE",
      "100": "#DDE6FE",
      "200": "#ADBFF5",
      "300": "#8FA6F0",
      "400": "#6F8AE8",
      "500": "#5277e2",
      "600": "#4567DD",
      "700": "#3C61DD",
      "800": "#385BCC",
      "900": "#3451B2",
      "950": "#243B8A"
    },
    "info": {
      "50": "#ECFEFF",
      "100": "#CFFAFE",
      "200": "#A5F3FC",
      "300": "#67E8F9",
      "400": "#22D3EE",
      "500": "#06B6D4",
      "600": "#0891B2",
      "700": "#0E7490",
      "800": "#155E75",
      "900": "#164E63",
      "950": "#083344"
    },
    "success": {
      "50": "#F0FDF4",
      "100": "#DCFCE7",
      "200": "#BBF7D0",
      "300": "#86EFAC",
      "400": "#4ADE80",
      "500": "#22C55E",
      "600": "#16A34A",
      "700": "#15803D",
      "800": "#166534",
      "900": "#14532D",
      "950": "#052E16"
    },
    "warning": {
      "50": "#FFFBEB",
      "100": "#FEF3C7",
      "200": "#FDE68A",
      "300": "#FCD34D",
      "400": "#FBBF24",
      "500": "#F59E0B",
      "600": "#D97706",
      "700": "#B45309",
      "800": "#92400E",
      "900": "#78350F",
      "950": "#451A03"
    },
    "danger": {
      "50": "#FEF2F2",
      "100": "#FEE2E2",
      "200": "#FECACA",
      "300": "#FCA5A5",
      "400": "#F87171",
      "500": "#EF4444",
      "600": "#DC2626",
      "700": "#B91C1C",
      "800": "#991B1B",
      "900": "#7F1D1D",
      "950": "#450A0A"
    },
    "white": "#FFFFFF",
    "black": "#000000",
    "transparent": "transparent",
    "surface": {
      "default": "#FFFFFF",
      "raised": "#FFFFFF",
      "sunken": "#F8F9FA",
      "overlay": "rgba(17, 24, 28, 0.40)",
      "inverse": "#11181C",
      "brand": "#3C61DD",
      "info-subtle": "#ECFEFF",
      "success-subtle": "#F0FDF4",
      "warning-subtle": "#FFFBEB",
      "danger-subtle": "#FEF2F2"
    },
    "text": {
      "primary": "#11181C",
      "secondary": "#4D5358",
      "tertiary": "#697177",
      "muted": "#889096",
      "disabled": "#C1C8CD",
      "inverse": "#FFFFFF",
      "on-brand": "#FFFFFF",
      "link": "#3C61DD",
      "link-hover": "#385BCC",
      "success": "#15803D",
      "warning": "#92400E",
      "danger": "#B91C1C",
      "info": "#0E7490"
    },
    "border": {
      "default": "#D7DBDF",
      "subtle": "#E6E8EB",
      "strong": "#C1C8CD",
      "focus": "#3C61DD",
      "disabled": "#E6E8EB",
      "error": "#DC2626",
      "success": "#16A34A",
      "warning": "#D97706",
      "info": "#0891B2"
    },
    "action": {
      "primary": {
        "bg": "#3C61DD",
        "bg-hover": "#385BCC",
        "bg-active": "#3451B2",
        "bg-disabled": "#ADBFF5",
        "fg": "#FFFFFF"
      },
      "secondary": {
        "bg": "#E6E8EB",
        "bg-hover": "#D7DBDF",
        "bg-active": "#C1C8CD",
        "bg-disabled": "#F0F2F4",
        "fg": "#11181C"
      },
      "tertiary": {
        "bg": "transparent",
        "bg-hover": "#F0F2F4",
        "bg-active": "#E6E8EB",
        "bg-disabled": "transparent",
        "fg": "#11181C"
      },
      "destructive": {
        "bg": "#DC2626",
        "bg-hover": "#B91C1C",
        "bg-active": "#991B1B",
        "bg-disabled": "#FECACA",
        "fg": "#FFFFFF"
      }
    },
    "feedback": {
      "info": {
        "bg": "#ECFEFF",
        "border": "#67E8F9",
        "fg": "#155E75",
        "icon": "#0891B2"
      },
      "success": {
        "bg": "#F0FDF4",
        "border": "#86EFAC",
        "fg": "#166534",
        "icon": "#16A34A"
      },
      "warning": {
        "bg": "#FFFBEB",
        "border": "#FCD34D",
        "fg": "#78350F",
        "icon": "#D97706"
      },
      "danger": {
        "bg": "#FEF2F2",
        "border": "#FCA5A5",
        "fg": "#991B1B",
        "icon": "#DC2626"
      }
    }
  },
  "space": {
    "0": "0",
    "1": "4px",
    "2": "8px",
    "3": "12px",
    "4": "16px",
    "5": "20px",
    "6": "24px",
    "8": "32px",
    "10": "40px",
    "12": "48px",
    "16": "64px",
    "20": "80px",
    "24": "96px",
    "32": "128px"
  },
  "font-family": {
    "sans": "system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
    "serif": "ui-serif, Georgia, \"Times New Roman\", serif",
    "mono": "ui-monospace, SFMono-Regular, Menlo, Consolas, \"Liberation Mono\", monospace"
  },
  "font-size": {
    "25": "10px",
    "50": "11px",
    "100": "12px",
    "200": "14px",
    "300": "16px",
    "400": "18px",
    "500": "20px",
    "600": "24px",
    "700": "30px",
    "800": "36px",
    "900": "48px"
  },
  "line-height": {
    "tight": "1.1",
    "snug": "1.25",
    "normal": "1.5",
    "relaxed": "1.625",
    "loose": "2"
  },
  "letter-spacing": {
    "tight": "-0.02em",
    "normal": "0",
    "wide": "0.04em",
    "wider": "0.08em"
  },
  "font-weight": {
    "regular": "400",
    "medium": "500",
    "semibold": "600",
    "bold": "700"
  },
  "radius": {
    "none": "0",
    "xs": "2px",
    "sm": "4px",
    "md": "6px",
    "lg": "8px",
    "xl": "12px",
    "2xl": "16px",
    "full": "9999px"
  },
  "border-width": {
    "0": "0",
    "1": "1px",
    "2": "2px",
    "4": "4px"
  },
  "shadow": {
    "0": "none",
    "1": "0 1px 2px 0 rgba(17, 24, 28, 0.04), 0 1px 1px 0 rgba(17, 24, 28, 0.04)",
    "2": "0 2px 4px 0 rgba(17, 24, 28, 0.06), 0 1px 2px 0 rgba(17, 24, 28, 0.04)",
    "3": "0 4px 8px 0 rgba(17, 24, 28, 0.08), 0 2px 4px 0 rgba(17, 24, 28, 0.04)",
    "4": "0 8px 16px 0 rgba(17, 24, 28, 0.10), 0 4px 8px 0 rgba(17, 24, 28, 0.06)",
    "5": "0 16px 32px 0 rgba(17, 24, 28, 0.14), 0 8px 16px 0 rgba(17, 24, 28, 0.08)"
  },
  "opacity": {
    "0": "0",
    "5": "0.05",
    "10": "0.1",
    "20": "0.2",
    "40": "0.4",
    "60": "0.6",
    "80": "0.8",
    "100": "1"
  },
  "duration": {
    "instant": "0ms",
    "fast": "100ms",
    "base": "200ms",
    "slow": "300ms",
    "slower": "500ms"
  },
  "ease": {
    "linear": "linear",
    "in": "cubic-bezier(0.4, 0, 1, 1)",
    "out": "cubic-bezier(0, 0, 0.2, 1)",
    "in-out": "cubic-bezier(0.4, 0, 0.2, 1)",
    "spring": "cubic-bezier(0.5, 1.5, 0.5, 1)"
  },
  "z": {
    "base": "0",
    "dropdown": "1000",
    "sticky": "1100",
    "overlay": "1200",
    "modal": "1300",
    "toast": "1400",
    "tooltip": "1500"
  },
  "breakpoint": {
    "sm": "640px",
    "md": "768px",
    "lg": "1024px",
    "xl": "1280px"
  },
  "elevation": {
    "e0": "none",
    "e1": "0 1px 2px 0 rgba(17, 24, 28, 0.04), 0 1px 1px 0 rgba(17, 24, 28, 0.04)",
    "e2": "0 2px 4px 0 rgba(17, 24, 28, 0.06), 0 1px 2px 0 rgba(17, 24, 28, 0.04)",
    "e3": "0 4px 8px 0 rgba(17, 24, 28, 0.08), 0 2px 4px 0 rgba(17, 24, 28, 0.04)",
    "e4": "0 8px 16px 0 rgba(17, 24, 28, 0.10), 0 4px 8px 0 rgba(17, 24, 28, 0.06)",
    "e5": "0 16px 32px 0 rgba(17, 24, 28, 0.14), 0 8px 16px 0 rgba(17, 24, 28, 0.08)"
  },
  "space-inset": {
    "sm": "8px",
    "md": "12px",
    "lg": "16px",
    "xl": "24px"
  },
  "space-stack": {
    "xs": "4px",
    "sm": "8px",
    "md": "12px",
    "lg": "16px",
    "xl": "24px"
  },
  "space-inline": {
    "xs": "4px",
    "sm": "8px",
    "md": "12px",
    "lg": "16px"
  },
  "text": {
    "web": {
      "display-l": {
        "size": "48px",
        "line": "53",
        "weight": "600"
      },
      "display-m": {
        "size": "36px",
        "line": "40",
        "weight": "600"
      },
      "display-s": {
        "size": "30px",
        "line": "33",
        "weight": "600"
      },
      "heading-1": {
        "size": "30px",
        "line": "38",
        "weight": "600"
      },
      "heading-2": {
        "size": "24px",
        "line": "30",
        "weight": "600"
      },
      "heading-3": {
        "size": "20px",
        "line": "25",
        "weight": "600"
      },
      "heading-4": {
        "size": "18px",
        "line": "23",
        "weight": "600"
      },
      "heading-5": {
        "size": "16px",
        "line": "20",
        "weight": "600"
      },
      "heading-6": {
        "size": "14px",
        "line": "18",
        "weight": "600"
      },
      "body-l": {
        "size": "18px",
        "line": "27",
        "weight": "400"
      },
      "body-m": {
        "size": "16px",
        "line": "24",
        "weight": "400"
      },
      "body-s": {
        "size": "14px",
        "line": "21",
        "weight": "400"
      },
      "label-l": {
        "size": "16px",
        "line": "20",
        "weight": "500"
      },
      "label-m": {
        "size": "14px",
        "line": "18",
        "weight": "500"
      },
      "label-s": {
        "size": "12px",
        "line": "15",
        "weight": "500"
      },
      "caption": {
        "size": "12px",
        "line": "18",
        "weight": "400"
      },
      "code": {
        "size": "14px",
        "line": "21",
        "weight": "400",
        "family": "ui-monospace, SFMono-Regular, Menlo, Consolas, \"Liberation Mono\", monospace"
      },
      "overline": {
        "size": "11px",
        "line": "14",
        "weight": "600",
        "spacing": "0.08em"
      }
    },
    "mobile": {
      "title-xl": {
        "size": "36px",
        "line": "40",
        "weight": "600"
      },
      "title-lg": {
        "size": "30px",
        "line": "38",
        "weight": "600"
      },
      "title-md": {
        "size": "24px",
        "line": "30",
        "weight": "600"
      },
      "title-sm": {
        "size": "20px",
        "line": "25",
        "weight": "500"
      },
      "headline": {
        "size": "16px",
        "line": "20",
        "weight": "600"
      },
      "body-lg-regular": {
        "size": "16px",
        "line": "24",
        "weight": "400"
      },
      "body-lg-semibold": {
        "size": "16px",
        "line": "24",
        "weight": "600"
      },
      "body-md-regular": {
        "size": "14px",
        "line": "21",
        "weight": "400"
      },
      "body-md-semibold": {
        "size": "14px",
        "line": "21",
        "weight": "600"
      },
      "body-sm-regular": {
        "size": "12px",
        "line": "18",
        "weight": "400"
      },
      "body-sm-semibold": {
        "size": "12px",
        "line": "18",
        "weight": "600"
      },
      "subhead-md": {
        "size": "14px",
        "line": "18",
        "weight": "600"
      },
      "subhead-sm": {
        "size": "12px",
        "line": "15",
        "weight": "600"
      },
      "label": {
        "size": "12px",
        "line": "15",
        "weight": "600"
      },
      "caption": {
        "size": "11px",
        "line": "17",
        "weight": "400"
      },
      "micro": {
        "size": "10px",
        "line": "15",
        "weight": "400"
      }
    }
  },
  "button": {
    "radius": "6px",
    "border-width": "1px",
    "font-family": "system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
    "font-weight": "500",
    "letter-spacing": "0",
    "icon-gap": "8px",
    "transition": "background-color 200ms cubic-bezier(0.4, 0, 0.2, 1), color 200ms cubic-bezier(0.4, 0, 0.2, 1), border-color 200ms cubic-bezier(0.4, 0, 0.2, 1), box-shadow 100ms cubic-bezier(0, 0, 0.2, 1)",
    "disabled-opacity": "0.6",
    "focus-ring": "0 0 0 2px #FFFFFF, 0 0 0 4px #3C61DD",
    "height": {
      "xs": "24px",
      "sm": "32px",
      "md": "40px",
      "lg": "48px",
      "xl": "56px"
    },
    "padding-inline": {
      "xs": "8px",
      "sm": "12px",
      "md": "16px",
      "lg": "20px",
      "xl": "24px"
    },
    "font-size": {
      "xs": "12px",
      "sm": "14px",
      "md": "14px",
      "lg": "16px",
      "xl": "18px"
    },
    "primary": {
      "bg": "#3C61DD",
      "bg-hover": "#385BCC",
      "bg-active": "#3451B2",
      "bg-disabled": "#ADBFF5",
      "fg": "#FFFFFF",
      "border": "#3C61DD"
    },
    "secondary": {
      "bg": "#E6E8EB",
      "bg-hover": "#D7DBDF",
      "bg-active": "#C1C8CD",
      "bg-disabled": "#F0F2F4",
      "fg": "#11181C",
      "border": "#D7DBDF"
    },
    "tertiary": {
      "bg": "transparent",
      "bg-hover": "#F0F2F4",
      "bg-active": "#E6E8EB",
      "bg-disabled": "transparent",
      "fg": "#11181C",
      "border": "transparent"
    },
    "destructive": {
      "bg": "#DC2626",
      "bg-hover": "#B91C1C",
      "bg-active": "#991B1B",
      "bg-disabled": "#FECACA",
      "fg": "#FFFFFF",
      "border": "#DC2626"
    },
    "destructive-secondary": {
      "bg": "transparent",
      "bg-hover": "#FEF2F2",
      "bg-active": "#FEE2E2",
      "bg-disabled": "transparent",
      "fg": "#B91C1C",
      "border": "#DC2626"
    },
    "link": {
      "bg": "transparent",
      "bg-hover": "transparent",
      "bg-active": "transparent",
      "bg-disabled": "transparent",
      "fg": "#3C61DD",
      "fg-hover": "#385BCC",
      "border": "transparent"
    }
  },
  "field": {
    "label": {
      "color": "#11181C",
      "size": "14px",
      "weight": "500",
      "line": "1.25",
      "gap": "8px"
    },
    "helper": {
      "color": "#697177",
      "size": "12px",
      "line": "1.5"
    },
    "error": {
      "color": "#B91C1C"
    },
    "success": {
      "color": "#15803D"
    },
    "required": {
      "color": "#B91C1C"
    },
    "stack-gap": "8px"
  },
  "input": {
    "bg": "#FFFFFF",
    "bg-disabled": "#F8F9FA",
    "fg": "#11181C",
    "fg-placeholder": "#889096",
    "fg-disabled": "#C1C8CD",
    "border": "#D7DBDF",
    "border-hover": "#C1C8CD",
    "border-focus": "#3C61DD",
    "border-error": "#DC2626",
    "border-success": "#16A34A",
    "border-disabled": "#E6E8EB",
    "radius": "6px",
    "border-width": "1px",
    "font-family": "system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
    "font-size": "14px",
    "line-height": "1.5",
    "transition": "border-color 100ms cubic-bezier(0, 0, 0.2, 1), box-shadow 100ms cubic-bezier(0, 0, 0.2, 1)",
    "focus-ring": "0 0 0 3px rgba(60, 97, 221, 0.20)",
    "focus-ring-error": "0 0 0 3px rgba(220, 38, 38, 0.20)",
    "icon-color": "#697177",
    "icon-gap": "8px",
    "height": {
      "sm": "32px",
      "md": "40px",
      "lg": "48px"
    },
    "padding-inline": {
      "sm": "8px",
      "md": "12px",
      "lg": "16px"
    }
  },
  "numeric": {
    "stepper-width": "28px",
    "stepper-bg": "#F8F9FA",
    "stepper-bg-hover": "#E6E8EB",
    "stepper-fg": "#4D5358"
  },
  "textarea": {
    "min-height": "80px",
    "padding-block": "8px"
  },
  "radio": {
    "size": "16px",
    "border": "#C1C8CD",
    "border-checked": "#3C61DD",
    "bg": "#FFFFFF",
    "bg-checked": "#3C61DD",
    "dot": "#FFFFFF",
    "bg-disabled": "#F8F9FA",
    "border-disabled": "#E6E8EB",
    "focus-ring": "0 0 0 3px rgba(60, 97, 221, 0.20)",
    "label-color": "#11181C",
    "label-gap": "8px",
    "group-gap": "12px"
  },
  "checkbox": {
    "size": "16px",
    "radius": "2px",
    "border": "#C1C8CD",
    "border-checked": "#3C61DD",
    "bg": "#FFFFFF",
    "bg-checked": "#3C61DD",
    "mark": "#FFFFFF",
    "bg-disabled": "#F8F9FA",
    "border-disabled": "#E6E8EB",
    "focus-ring": "0 0 0 3px rgba(60, 97, 221, 0.20)",
    "label-color": "#11181C",
    "label-gap": "8px",
    "group-gap": "12px"
  },
  "toast": {
    "bg": "#FFFFFF",
    "fg": "#11181C",
    "border": "#E6E8EB",
    "radius": "8px",
    "shadow": "0 4px 8px 0 rgba(17, 24, 28, 0.08), 0 2px 4px 0 rgba(17, 24, 28, 0.04)",
    "padding": "12px 16px",
    "min-width": "320px",
    "max-width": "480px",
    "gap": "12px",
    "stack-gap": "8px",
    "z": "1400",
    "info-icon": "#0891B2",
    "success-icon": "#16A34A",
    "warning-icon": "#D97706",
    "danger-icon": "#DC2626",
    "neutral-icon": "#697177",
    "info-accent": "#0891B2",
    "success-accent": "#16A34A",
    "warning-accent": "#D97706",
    "danger-accent": "#DC2626",
    "neutral-accent": "#C1C8CD"
  },
  "badge": {
    "radius": "9999px",
    "font-family": "system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
    "font-weight": "500",
    "icon-gap": "4px",
    "padding-inline": {
      "xs": "8px",
      "sm": "8px",
      "md": "12px"
    },
    "height": {
      "xs": "18px",
      "sm": "22px",
      "md": "26px"
    },
    "font-size": {
      "xs": "11px",
      "sm": "12px",
      "md": "14px"
    }
  },
  "tag": {
    "radius": "6px",
    "bg-hover-tint": "rgba(0, 0, 0, 0.04)",
    "remove-hover-bg": "rgba(0, 0, 0, 0.08)",
    "focus-ring": "0 0 0 3px rgba(60, 97, 221, 0.20)"
  },
  "tabs": {
    "gap": "4px",
    "list-bg-segmented": "#F8F9FA",
    "trigger-fg": "#4D5358",
    "trigger-fg-active": "#11181C",
    "trigger-fg-hover": "#11181C",
    "trigger-fg-disabled": "#C1C8CD",
    "underline-color": "#3C61DD",
    "pill-bg-active": "#3C61DD",
    "pill-fg-active": "#FFFFFF",
    "segmented-bg-active": "#FFFFFF",
    "trigger-padding": {
      "sm": "8px 12px",
      "md": "12px 16px",
      "lg": "12px 20px"
    },
    "trigger-font": {
      "sm": "12px",
      "md": "14px",
      "lg": "16px"
    },
    "trigger-radius": "6px",
    "list-radius": "6px",
    "trigger-transition": "color 100ms cubic-bezier(0, 0, 0.2, 1), background-color 100ms cubic-bezier(0, 0, 0.2, 1)"
  },
  "dropdown": {
    "bg": "#FFFFFF",
    "border": "#E6E8EB",
    "radius": "6px",
    "shadow": "0 4px 8px 0 rgba(17, 24, 28, 0.08), 0 2px 4px 0 rgba(17, 24, 28, 0.04)",
    "z": "1000",
    "padding": "4px",
    "min-width": "180px",
    "max-height": "320px",
    "item-fg": "#11181C",
    "item-fg-active": "#11181C",
    "item-bg-hover": "#F8F9FA",
    "item-bg-active": "#EEF2FE",
    "item-fg-disabled": "#C1C8CD",
    "item-fg-destructive": "#B91C1C",
    "item-bg-destructive-hover": "#FEF2F2",
    "item-padding": "8px 12px",
    "item-radius": "4px",
    "item-gap": "8px",
    "divider-color": "#E6E8EB",
    "shortcut-color": "#889096"
  },
  "select": {
    "trigger-bg": "#FFFFFF",
    "trigger-fg": "#11181C",
    "trigger-border": "#D7DBDF",
    "trigger-radius": "6px",
    "trigger-padding": "8px 12px",
    "chip-bg": "#F0F2F4",
    "chip-fg": "#11181C",
    "chip-radius": "4px",
    "chip-padding": "4px 8px"
  },
  "progress": {
    "track-bg": "#E6E8EB",
    "radius": "9999px",
    "height": {
      "xs": "4px",
      "sm": "6px",
      "md": "8px",
      "lg": "12px"
    },
    "fill-brand": "#3C61DD",
    "fill-success": "#16A34A",
    "fill-warning": "#D97706",
    "fill-danger": "#DC2626",
    "label-color": "#4D5358",
    "label-size": "12px",
    "segment-gap": "4px",
    "circular-track": "#E6E8EB",
    "indeterminate-duration": "1500ms"
  }
} as const,
  dark: {
  "color": {
    "neutral": {
      "50": "#F8F9FA",
      "100": "#F0F2F4",
      "200": "#E6E8EB",
      "300": "#D7DBDF",
      "400": "#C1C8CD",
      "500": "#889096",
      "600": "#697177",
      "700": "#4D5358",
      "800": "#2C3338",
      "900": "#1A1F23",
      "950": "#11181C"
    },
    "brand": {
      "50": "#EEF2FE",
      "100": "#DDE6FE",
      "200": "#ADBFF5",
      "300": "#8FA6F0",
      "400": "#6F8AE8",
      "500": "#5277e2",
      "600": "#4567DD",
      "700": "#3C61DD",
      "800": "#385BCC",
      "900": "#3451B2",
      "950": "#243B8A"
    },
    "info": {
      "50": "#ECFEFF",
      "100": "#CFFAFE",
      "200": "#A5F3FC",
      "300": "#67E8F9",
      "400": "#22D3EE",
      "500": "#06B6D4",
      "600": "#0891B2",
      "700": "#0E7490",
      "800": "#155E75",
      "900": "#164E63",
      "950": "#083344"
    },
    "success": {
      "50": "#F0FDF4",
      "100": "#DCFCE7",
      "200": "#BBF7D0",
      "300": "#86EFAC",
      "400": "#4ADE80",
      "500": "#22C55E",
      "600": "#16A34A",
      "700": "#15803D",
      "800": "#166534",
      "900": "#14532D",
      "950": "#052E16"
    },
    "warning": {
      "50": "#FFFBEB",
      "100": "#FEF3C7",
      "200": "#FDE68A",
      "300": "#FCD34D",
      "400": "#FBBF24",
      "500": "#F59E0B",
      "600": "#D97706",
      "700": "#B45309",
      "800": "#92400E",
      "900": "#78350F",
      "950": "#451A03"
    },
    "danger": {
      "50": "#FEF2F2",
      "100": "#FEE2E2",
      "200": "#FECACA",
      "300": "#FCA5A5",
      "400": "#F87171",
      "500": "#EF4444",
      "600": "#DC2626",
      "700": "#B91C1C",
      "800": "#991B1B",
      "900": "#7F1D1D",
      "950": "#450A0A"
    },
    "white": "#FFFFFF",
    "black": "#000000",
    "transparent": "transparent",
    "surface": {
      "default": "#1A1F23",
      "raised": "#2C3338",
      "sunken": "#11181C",
      "overlay": "rgba(0, 0, 0, 0.60)",
      "inverse": "#FFFFFF",
      "brand": "#4567DD",
      "info-subtle": "#083344",
      "success-subtle": "#052E16",
      "warning-subtle": "#451A03",
      "danger-subtle": "#450A0A"
    },
    "text": {
      "primary": "#F8F9FA",
      "secondary": "#E6E8EB",
      "tertiary": "#D7DBDF",
      "muted": "#C1C8CD",
      "disabled": "#697177",
      "inverse": "#11181C",
      "on-brand": "#FFFFFF",
      "link": "#8FA6F0",
      "link-hover": "#ADBFF5",
      "success": "#86EFAC",
      "warning": "#FCD34D",
      "danger": "#FCA5A5",
      "info": "#67E8F9"
    },
    "border": {
      "default": "#4D5358",
      "subtle": "#2C3338",
      "strong": "#697177",
      "focus": "#6F8AE8",
      "disabled": "#2C3338",
      "error": "#F87171",
      "success": "#4ADE80",
      "warning": "#FBBF24",
      "info": "#22D3EE"
    },
    "action": {
      "primary": {
        "bg": "#4567DD",
        "bg-hover": "#5277e2",
        "bg-active": "#6F8AE8",
        "bg-disabled": "#3451B2",
        "fg": "#FFFFFF"
      },
      "secondary": {
        "bg": "#2C3338",
        "bg-hover": "#4D5358",
        "bg-active": "#697177",
        "bg-disabled": "#1A1F23",
        "fg": "#F8F9FA"
      },
      "tertiary": {
        "bg": "transparent",
        "bg-hover": "#2C3338",
        "bg-active": "#4D5358",
        "bg-disabled": "transparent",
        "fg": "#F8F9FA"
      },
      "destructive": {
        "bg": "#DC2626",
        "bg-hover": "#EF4444",
        "bg-active": "#F87171",
        "bg-disabled": "#7F1D1D",
        "fg": "#FFFFFF"
      }
    },
    "feedback": {
      "info": {
        "bg": "#083344",
        "border": "#0E7490",
        "fg": "#A5F3FC",
        "icon": "#22D3EE"
      },
      "success": {
        "bg": "#052E16",
        "border": "#15803D",
        "fg": "#BBF7D0",
        "icon": "#4ADE80"
      },
      "warning": {
        "bg": "#451A03",
        "border": "#B45309",
        "fg": "#FDE68A",
        "icon": "#FBBF24"
      },
      "danger": {
        "bg": "#450A0A",
        "border": "#B91C1C",
        "fg": "#FECACA",
        "icon": "#F87171"
      }
    }
  },
  "space": {
    "0": "0",
    "1": "4px",
    "2": "8px",
    "3": "12px",
    "4": "16px",
    "5": "20px",
    "6": "24px",
    "8": "32px",
    "10": "40px",
    "12": "48px",
    "16": "64px",
    "20": "80px",
    "24": "96px",
    "32": "128px"
  },
  "font-family": {
    "sans": "system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
    "serif": "ui-serif, Georgia, \"Times New Roman\", serif",
    "mono": "ui-monospace, SFMono-Regular, Menlo, Consolas, \"Liberation Mono\", monospace"
  },
  "font-size": {
    "25": "10px",
    "50": "11px",
    "100": "12px",
    "200": "14px",
    "300": "16px",
    "400": "18px",
    "500": "20px",
    "600": "24px",
    "700": "30px",
    "800": "36px",
    "900": "48px"
  },
  "line-height": {
    "tight": "1.1",
    "snug": "1.25",
    "normal": "1.5",
    "relaxed": "1.625",
    "loose": "2"
  },
  "letter-spacing": {
    "tight": "-0.02em",
    "normal": "0",
    "wide": "0.04em",
    "wider": "0.08em"
  },
  "font-weight": {
    "regular": "400",
    "medium": "500",
    "semibold": "600",
    "bold": "700"
  },
  "radius": {
    "none": "0",
    "xs": "2px",
    "sm": "4px",
    "md": "6px",
    "lg": "8px",
    "xl": "12px",
    "2xl": "16px",
    "full": "9999px"
  },
  "border-width": {
    "0": "0",
    "1": "1px",
    "2": "2px",
    "4": "4px"
  },
  "shadow": {
    "0": "none",
    "1": "0 1px 2px 0 rgba(17, 24, 28, 0.04), 0 1px 1px 0 rgba(17, 24, 28, 0.04)",
    "2": "0 2px 4px 0 rgba(17, 24, 28, 0.06), 0 1px 2px 0 rgba(17, 24, 28, 0.04)",
    "3": "0 4px 8px 0 rgba(17, 24, 28, 0.08), 0 2px 4px 0 rgba(17, 24, 28, 0.04)",
    "4": "0 8px 16px 0 rgba(17, 24, 28, 0.10), 0 4px 8px 0 rgba(17, 24, 28, 0.06)",
    "5": "0 16px 32px 0 rgba(17, 24, 28, 0.14), 0 8px 16px 0 rgba(17, 24, 28, 0.08)"
  },
  "opacity": {
    "0": "0",
    "5": "0.05",
    "10": "0.1",
    "20": "0.2",
    "40": "0.4",
    "60": "0.6",
    "80": "0.8",
    "100": "1"
  },
  "duration": {
    "instant": "0ms",
    "fast": "100ms",
    "base": "200ms",
    "slow": "300ms",
    "slower": "500ms"
  },
  "ease": {
    "linear": "linear",
    "in": "cubic-bezier(0.4, 0, 1, 1)",
    "out": "cubic-bezier(0, 0, 0.2, 1)",
    "in-out": "cubic-bezier(0.4, 0, 0.2, 1)",
    "spring": "cubic-bezier(0.5, 1.5, 0.5, 1)"
  },
  "z": {
    "base": "0",
    "dropdown": "1000",
    "sticky": "1100",
    "overlay": "1200",
    "modal": "1300",
    "toast": "1400",
    "tooltip": "1500"
  },
  "breakpoint": {
    "sm": "640px",
    "md": "768px",
    "lg": "1024px",
    "xl": "1280px"
  },
  "elevation": {
    "e0": "none",
    "e1": "0 1px 2px 0 rgba(17, 24, 28, 0.04), 0 1px 1px 0 rgba(17, 24, 28, 0.04)",
    "e2": "0 2px 4px 0 rgba(17, 24, 28, 0.06), 0 1px 2px 0 rgba(17, 24, 28, 0.04)",
    "e3": "0 4px 8px 0 rgba(17, 24, 28, 0.08), 0 2px 4px 0 rgba(17, 24, 28, 0.04)",
    "e4": "0 8px 16px 0 rgba(17, 24, 28, 0.10), 0 4px 8px 0 rgba(17, 24, 28, 0.06)",
    "e5": "0 16px 32px 0 rgba(17, 24, 28, 0.14), 0 8px 16px 0 rgba(17, 24, 28, 0.08)"
  },
  "space-inset": {
    "sm": "8px",
    "md": "12px",
    "lg": "16px",
    "xl": "24px"
  },
  "space-stack": {
    "xs": "4px",
    "sm": "8px",
    "md": "12px",
    "lg": "16px",
    "xl": "24px"
  },
  "space-inline": {
    "xs": "4px",
    "sm": "8px",
    "md": "12px",
    "lg": "16px"
  },
  "text": {
    "web": {
      "display-l": {
        "size": "48px",
        "line": "53",
        "weight": "600"
      },
      "display-m": {
        "size": "36px",
        "line": "40",
        "weight": "600"
      },
      "display-s": {
        "size": "30px",
        "line": "33",
        "weight": "600"
      },
      "heading-1": {
        "size": "30px",
        "line": "38",
        "weight": "600"
      },
      "heading-2": {
        "size": "24px",
        "line": "30",
        "weight": "600"
      },
      "heading-3": {
        "size": "20px",
        "line": "25",
        "weight": "600"
      },
      "heading-4": {
        "size": "18px",
        "line": "23",
        "weight": "600"
      },
      "heading-5": {
        "size": "16px",
        "line": "20",
        "weight": "600"
      },
      "heading-6": {
        "size": "14px",
        "line": "18",
        "weight": "600"
      },
      "body-l": {
        "size": "18px",
        "line": "27",
        "weight": "400"
      },
      "body-m": {
        "size": "16px",
        "line": "24",
        "weight": "400"
      },
      "body-s": {
        "size": "14px",
        "line": "21",
        "weight": "400"
      },
      "label-l": {
        "size": "16px",
        "line": "20",
        "weight": "500"
      },
      "label-m": {
        "size": "14px",
        "line": "18",
        "weight": "500"
      },
      "label-s": {
        "size": "12px",
        "line": "15",
        "weight": "500"
      },
      "caption": {
        "size": "12px",
        "line": "18",
        "weight": "400"
      },
      "code": {
        "size": "14px",
        "line": "21",
        "weight": "400",
        "family": "ui-monospace, SFMono-Regular, Menlo, Consolas, \"Liberation Mono\", monospace"
      },
      "overline": {
        "size": "11px",
        "line": "14",
        "weight": "600",
        "spacing": "0.08em"
      }
    },
    "mobile": {
      "title-xl": {
        "size": "36px",
        "line": "40",
        "weight": "600"
      },
      "title-lg": {
        "size": "30px",
        "line": "38",
        "weight": "600"
      },
      "title-md": {
        "size": "24px",
        "line": "30",
        "weight": "600"
      },
      "title-sm": {
        "size": "20px",
        "line": "25",
        "weight": "500"
      },
      "headline": {
        "size": "16px",
        "line": "20",
        "weight": "600"
      },
      "body-lg-regular": {
        "size": "16px",
        "line": "24",
        "weight": "400"
      },
      "body-lg-semibold": {
        "size": "16px",
        "line": "24",
        "weight": "600"
      },
      "body-md-regular": {
        "size": "14px",
        "line": "21",
        "weight": "400"
      },
      "body-md-semibold": {
        "size": "14px",
        "line": "21",
        "weight": "600"
      },
      "body-sm-regular": {
        "size": "12px",
        "line": "18",
        "weight": "400"
      },
      "body-sm-semibold": {
        "size": "12px",
        "line": "18",
        "weight": "600"
      },
      "subhead-md": {
        "size": "14px",
        "line": "18",
        "weight": "600"
      },
      "subhead-sm": {
        "size": "12px",
        "line": "15",
        "weight": "600"
      },
      "label": {
        "size": "12px",
        "line": "15",
        "weight": "600"
      },
      "caption": {
        "size": "11px",
        "line": "17",
        "weight": "400"
      },
      "micro": {
        "size": "10px",
        "line": "15",
        "weight": "400"
      }
    }
  },
  "button": {
    "radius": "6px",
    "border-width": "1px",
    "font-family": "system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
    "font-weight": "500",
    "letter-spacing": "0",
    "icon-gap": "8px",
    "transition": "background-color 200ms cubic-bezier(0.4, 0, 0.2, 1), color 200ms cubic-bezier(0.4, 0, 0.2, 1), border-color 200ms cubic-bezier(0.4, 0, 0.2, 1), box-shadow 100ms cubic-bezier(0, 0, 0.2, 1)",
    "disabled-opacity": "0.6",
    "focus-ring": "0 0 0 2px #1A1F23, 0 0 0 4px #6F8AE8",
    "height": {
      "xs": "24px",
      "sm": "32px",
      "md": "40px",
      "lg": "48px",
      "xl": "56px"
    },
    "padding-inline": {
      "xs": "8px",
      "sm": "12px",
      "md": "16px",
      "lg": "20px",
      "xl": "24px"
    },
    "font-size": {
      "xs": "12px",
      "sm": "14px",
      "md": "14px",
      "lg": "16px",
      "xl": "18px"
    },
    "primary": {
      "bg": "#4567DD",
      "bg-hover": "#5277e2",
      "bg-active": "#6F8AE8",
      "bg-disabled": "#3451B2",
      "fg": "#FFFFFF",
      "border": "#4567DD"
    },
    "secondary": {
      "bg": "#2C3338",
      "bg-hover": "#4D5358",
      "bg-active": "#697177",
      "bg-disabled": "#1A1F23",
      "fg": "#F8F9FA",
      "border": "#4D5358"
    },
    "tertiary": {
      "bg": "transparent",
      "bg-hover": "#2C3338",
      "bg-active": "#4D5358",
      "bg-disabled": "transparent",
      "fg": "#F8F9FA",
      "border": "transparent"
    },
    "destructive": {
      "bg": "#DC2626",
      "bg-hover": "#EF4444",
      "bg-active": "#F87171",
      "bg-disabled": "#7F1D1D",
      "fg": "#FFFFFF",
      "border": "#DC2626"
    },
    "destructive-secondary": {
      "bg": "transparent",
      "bg-hover": "#450A0A",
      "bg-active": "#FEE2E2",
      "bg-disabled": "transparent",
      "fg": "#FCA5A5",
      "border": "#F87171"
    },
    "link": {
      "bg": "transparent",
      "bg-hover": "transparent",
      "bg-active": "transparent",
      "bg-disabled": "transparent",
      "fg": "#8FA6F0",
      "fg-hover": "#ADBFF5",
      "border": "transparent"
    }
  },
  "field": {
    "label": {
      "color": "#F8F9FA",
      "size": "14px",
      "weight": "500",
      "line": "1.25",
      "gap": "8px"
    },
    "helper": {
      "color": "#D7DBDF",
      "size": "12px",
      "line": "1.5"
    },
    "error": {
      "color": "#FCA5A5"
    },
    "success": {
      "color": "#86EFAC"
    },
    "required": {
      "color": "#FCA5A5"
    },
    "stack-gap": "8px"
  },
  "input": {
    "bg": "#1A1F23",
    "bg-disabled": "#11181C",
    "fg": "#F8F9FA",
    "fg-placeholder": "#C1C8CD",
    "fg-disabled": "#697177",
    "border": "#4D5358",
    "border-hover": "#697177",
    "border-focus": "#6F8AE8",
    "border-error": "#F87171",
    "border-success": "#4ADE80",
    "border-disabled": "#2C3338",
    "radius": "6px",
    "border-width": "1px",
    "font-family": "system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
    "font-size": "14px",
    "line-height": "1.5",
    "transition": "border-color 100ms cubic-bezier(0, 0, 0.2, 1), box-shadow 100ms cubic-bezier(0, 0, 0.2, 1)",
    "focus-ring": "0 0 0 3px rgba(143, 166, 240, 0.30)",
    "focus-ring-error": "0 0 0 3px rgba(248, 113, 113, 0.30)",
    "icon-color": "#D7DBDF",
    "icon-gap": "8px",
    "height": {
      "sm": "32px",
      "md": "40px",
      "lg": "48px"
    },
    "padding-inline": {
      "sm": "8px",
      "md": "12px",
      "lg": "16px"
    }
  },
  "numeric": {
    "stepper-width": "28px",
    "stepper-bg": "#2C3338",
    "stepper-bg-hover": "#4D5358",
    "stepper-fg": "#E6E8EB"
  },
  "textarea": {
    "min-height": "80px",
    "padding-block": "8px"
  },
  "radio": {
    "size": "16px",
    "border": "#697177",
    "border-checked": "#4567DD",
    "bg": "#1A1F23",
    "bg-checked": "#4567DD",
    "dot": "#FFFFFF",
    "bg-disabled": "#11181C",
    "border-disabled": "#2C3338",
    "focus-ring": "0 0 0 3px rgba(143, 166, 240, 0.30)",
    "label-color": "#F8F9FA",
    "label-gap": "8px",
    "group-gap": "12px"
  },
  "checkbox": {
    "size": "16px",
    "radius": "2px",
    "border": "#697177",
    "border-checked": "#4567DD",
    "bg": "#1A1F23",
    "bg-checked": "#4567DD",
    "mark": "#FFFFFF",
    "bg-disabled": "#11181C",
    "border-disabled": "#2C3338",
    "focus-ring": "0 0 0 3px rgba(143, 166, 240, 0.30)",
    "label-color": "#F8F9FA",
    "label-gap": "8px",
    "group-gap": "12px"
  },
  "toast": {
    "bg": "#2C3338",
    "fg": "#F8F9FA",
    "border": "#2C3338",
    "radius": "8px",
    "shadow": "0 4px 8px 0 rgba(17, 24, 28, 0.08), 0 2px 4px 0 rgba(17, 24, 28, 0.04)",
    "padding": "12px 16px",
    "min-width": "320px",
    "max-width": "480px",
    "gap": "12px",
    "stack-gap": "8px",
    "z": "1400",
    "info-icon": "#22D3EE",
    "success-icon": "#4ADE80",
    "warning-icon": "#FBBF24",
    "danger-icon": "#F87171",
    "neutral-icon": "#D7DBDF",
    "info-accent": "#0891B2",
    "success-accent": "#16A34A",
    "warning-accent": "#D97706",
    "danger-accent": "#DC2626",
    "neutral-accent": "#C1C8CD"
  },
  "badge": {
    "radius": "9999px",
    "font-family": "system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
    "font-weight": "500",
    "icon-gap": "4px",
    "padding-inline": {
      "xs": "8px",
      "sm": "8px",
      "md": "12px"
    },
    "height": {
      "xs": "18px",
      "sm": "22px",
      "md": "26px"
    },
    "font-size": {
      "xs": "11px",
      "sm": "12px",
      "md": "14px"
    }
  },
  "tag": {
    "radius": "6px",
    "bg-hover-tint": "rgba(255, 255, 255, 0.06)",
    "remove-hover-bg": "rgba(255, 255, 255, 0.10)",
    "focus-ring": "0 0 0 3px rgba(143, 166, 240, 0.30)"
  },
  "tabs": {
    "gap": "4px",
    "list-bg-segmented": "#11181C",
    "trigger-fg": "#E6E8EB",
    "trigger-fg-active": "#F8F9FA",
    "trigger-fg-hover": "#F8F9FA",
    "trigger-fg-disabled": "#697177",
    "underline-color": "#4567DD",
    "pill-bg-active": "#4567DD",
    "pill-fg-active": "#FFFFFF",
    "segmented-bg-active": "#1A1F23",
    "trigger-padding": {
      "sm": "8px 12px",
      "md": "12px 16px",
      "lg": "12px 20px"
    },
    "trigger-font": {
      "sm": "12px",
      "md": "14px",
      "lg": "16px"
    },
    "trigger-radius": "6px",
    "list-radius": "6px",
    "trigger-transition": "color 100ms cubic-bezier(0, 0, 0.2, 1), background-color 100ms cubic-bezier(0, 0, 0.2, 1)"
  },
  "dropdown": {
    "bg": "#2C3338",
    "border": "#2C3338",
    "radius": "6px",
    "shadow": "0 4px 8px 0 rgba(17, 24, 28, 0.08), 0 2px 4px 0 rgba(17, 24, 28, 0.04)",
    "z": "1000",
    "padding": "4px",
    "min-width": "180px",
    "max-height": "320px",
    "item-fg": "#F8F9FA",
    "item-fg-active": "#F8F9FA",
    "item-bg-hover": "#11181C",
    "item-bg-active": "#2C3338",
    "item-fg-disabled": "#697177",
    "item-fg-destructive": "#FCA5A5",
    "item-bg-destructive-hover": "#450A0A",
    "item-padding": "8px 12px",
    "item-radius": "4px",
    "item-gap": "8px",
    "divider-color": "#2C3338",
    "shortcut-color": "#C1C8CD"
  },
  "select": {
    "trigger-bg": "#1A1F23",
    "trigger-fg": "#F8F9FA",
    "trigger-border": "#4D5358",
    "trigger-radius": "6px",
    "trigger-padding": "8px 12px",
    "chip-bg": "#2C3338",
    "chip-fg": "#F8F9FA",
    "chip-radius": "4px",
    "chip-padding": "4px 8px"
  },
  "progress": {
    "track-bg": "#2C3338",
    "radius": "9999px",
    "height": {
      "xs": "4px",
      "sm": "6px",
      "md": "8px",
      "lg": "12px"
    },
    "fill-brand": "#3C61DD",
    "fill-success": "#16A34A",
    "fill-warning": "#D97706",
    "fill-danger": "#DC2626",
    "label-color": "#E6E8EB",
    "label-size": "12px",
    "segment-gap": "4px",
    "circular-track": "#2C3338",
    "indeterminate-duration": "1500ms"
  }
} as const,
} as const;

export type Theme = typeof themes.light;
