#!/usr/bin/env node
/**
 * Illustration build — two source lanes, unified consumer API.
 *
 * VECTOR lane  (packages/illustrations/svg/*.svg)
 *   Multi-color artwork; colors preserved. Produces per-illustration web
 *   component (dangerouslySetInnerHTML, keeps full SVG feature set) and
 *   RN component (SvgXml from react-native-svg). Aspect ratio preserved
 *   from the SVG viewBox; width prop controls size, height auto-computed.
 *
 * RASTER lane  (packages/illustrations/raster-src/*.{png,jpg,jpeg})
 *   AI-generated raster art. Converted to WebP via sharp:
 *     raster/<name>.webp    = 1× (source resized to 50%)
 *     raster/<name>@2x.webp = 2× (source at original resolution)
 *   Committed to the repo; no CDN required at this stage.
 *   Web component: <img srcSet> via require().
 *   RN component: <Image> via require() (Metro @2x convention).
 *
 * UNIFIED
 *   manifest.ts              name → { type, width, height, src?, src2x? }
 *   src/web/Illustration.tsx  unified web component  (<Illustration name="…" />)
 *   src/native/Illustration.tsx unified RN component
 *   src/web/index.ts + src/native/index.ts  barrels
 *   index.ts + native.ts    root entry points
 *
 * Zero runtime deps; devDep: sharp (raster lane only).
 * Run: node packages/illustrations/build.mjs
 */

import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join, extname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SVG_DIR    = join(__dirname, 'svg');
const RASTER_SRC = join(__dirname, 'raster-src');
const RASTER_OUT = join(__dirname, 'raster');
const WEB_DIR    = join(__dirname, 'src', 'web');
const NAT_DIR    = join(__dirname, 'src', 'native');

for (const d of [WEB_DIR, NAT_DIR, RASTER_OUT]) mkdirSync(d, { recursive: true });

const HEADER = `// AUTO-GENERATED by packages/illustrations/build.mjs — DO NOT EDIT BY HAND.
// Source: packages/illustrations/svg/ or raster-src/. Run \`npm run illustrations:build\`.

`;

/* ── Helpers ── */

function kebabToTitle(s) {
  return s.split('-').map(w => w[0].toUpperCase() + w.slice(1)).join('');
}

/**
 * Parse SVG viewBox → { vbW, vbH, aspectStr }.
 * Falls back to width/height attributes; defaults to 240×180 if absent.
 */
function parseSVGDimensions(svgStr) {
  const vbMatch = svgStr.match(/viewBox="([\d\s.,-]+)"/i);
  if (vbMatch) {
    const [, minX, minY, w, h] = vbMatch[1].trim().split(/[\s,]+/).map(Number);
    if (w && h) return { vbW: w, vbH: h, aspectStr: `${w}/${h}` };
  }
  const wMatch = svgStr.match(/\swidth="([\d.]+)"/i);
  const hMatch = svgStr.match(/\sheight="([\d.]+)"/i);
  const w = wMatch ? parseFloat(wMatch[1]) : 240;
  const h = hMatch ? parseFloat(hMatch[1]) : 180;
  return { vbW: w, vbH: h, aspectStr: `${w}/${h}` };
}

/**
 * Clean an SVG string for embedding:
 *  - Strip XML declaration, DOCTYPE, comments, metadata, title, desc.
 *  - Strip editor namespaces (Inkscape, Illustrator, Sketch …).
 *  - Remove explicit width/height from the root <svg>; add width/height="100%"
 *    so the element fills its container (set via the wrapping <span>'s style).
 *  - Collapse multiple blanks (keep single spaces within attr values).
 *  - Colors are NEVER touched — multi-color illustrations preserved as-is.
 */
function cleanSVG(raw) {
  let s = raw.trim();
  s = s.replace(/<\?xml[^?]*\?>\s*/gi, '');
  s = s.replace(/<!DOCTYPE[^>]*>\s*/gi, '');
  s = s.replace(/<!--[\s\S]*?-->/g, '');
  s = s.replace(/<metadata[\s\S]*?<\/metadata>/gi, '');
  s = s.replace(/<title>[\s\S]*?<\/title>/gi, '');
  s = s.replace(/<desc>[\s\S]*?<\/desc>/gi, '');
  // Editor-specific namespaces / attributes
  s = s.replace(/\s+(?:inkscape|sodipodi|sketch|dc|cc|rdf):[\w-]+="[^"]*"/g, '');
  s = s.replace(/\s+xmlns:(?:inkscape|sodipodi|sketch|xlink|dc|cc|rdf)="[^"]*"/g, '');
  s = s.replace(/<(?:inkscape|sodipodi|sketch):[\s\S]*?(?:\/>|>[\s\S]*?<\/(?:inkscape|sodipodi|sketch):[^>]+>)/g, '');
  // Root <svg> element: strip width/height, add 100% so parent controls size
  s = s.replace(/<svg([^>]*)>/, (_, attrs) => {
    attrs = attrs.replace(/\s+width="[^"]*"/g, '');
    attrs = attrs.replace(/\s+height="[^"]*"/g, '');
    return `<svg${attrs} width="100%" height="100%">`;
  });
  // Collapse runs of whitespace outside attribute values (best-effort)
  s = s.replace(/\n\s*\n/g, '\n');
  if (!s.endsWith('\n')) s += '\n';
  return s;
}

/* ── SVG lane ── */

const svgFiles = existsSync(SVG_DIR)
  ? readdirSync(SVG_DIR).filter(f => f.endsWith('.svg')).sort()
  : [];

const svgItems = svgFiles.map(f => {
  const name  = f.replace('.svg', '');
  const title = kebabToTitle(name);
  const raw   = readFileSync(join(SVG_DIR, f), 'utf8');
  const { vbW, vbH, aspectStr } = parseSVGDimensions(raw);
  const svg   = cleanSVG(raw);
  return { name, title, vbW, vbH, aspectStr, svg, type: 'svg' };
});

// Web components — embed cleaned SVG via dangerouslySetInnerHTML.
// The outer <span> owns width + aspect-ratio; the inner <svg> fills it via 100%/100%.
for (const { title, vbW, vbH, aspectStr, svg } of svgItems) {
  const svgJson = JSON.stringify(svg);
  const src = `${HEADER}import * as React from 'react';

const _svg = ${svgJson};

export interface ${title}Props {
  /** Rendered width. Height is calculated automatically (intrinsic ratio ${vbW}∶${vbH}). */
  width?: number | string;
  /** Accessible label. Omit for purely decorative illustrations. */
  alt?: string;
  className?: string;
  style?: React.CSSProperties;
}

export function ${title}({ width = ${vbW}, alt, className, style }: ${title}Props) {
  return (
    <span
      role={alt ? 'img' : 'presentation'}
      aria-label={alt}
      aria-hidden={!alt}
      className={className}
      style={{ display: 'inline-block', width, aspectRatio: '${aspectStr}', overflow: 'hidden', flexShrink: 0, ...style }}
      // eslint-disable-next-line react/no-danger
      dangerouslySetInnerHTML={{ __html: _svg }}
    />
  );
}
`;
  writeFileSync(join(WEB_DIR, `${title}.tsx`), src);
}

// Native components — pass SVG string to SvgXml; handles all features incl. gradients.
for (const { title, vbW, vbH, svg } of svgItems) {
  const svgJson = JSON.stringify(svg);
  const src = `${HEADER}import * as React from 'react';
import { SvgXml } from 'react-native-svg';

const _svgXml = ${svgJson};
const _aspect = ${vbH} / ${vbW};

export interface ${title}Props {
  /** Rendered width in dp. Height derived from intrinsic ratio (${vbW}∶${vbH}). */
  width?: number;
  accessibilityLabel?: string;
}

export function ${title}({ width = ${vbW}, accessibilityLabel }: ${title}Props) {
  const height = Math.round(width * _aspect);
  return (
    <SvgXml
      xml={_svgXml}
      width={width}
      height={height}
      accessible={!!accessibilityLabel}
      accessibilityLabel={accessibilityLabel}
    />
  );
}
`;
  writeFileSync(join(NAT_DIR, `${title}.tsx`), src);
}

/* ── Raster lane ── */

const RASTER_EXTS = new Set(['.png', '.jpg', '.jpeg', '.webp']);

const rasterSrcFiles = existsSync(RASTER_SRC)
  ? readdirSync(RASTER_SRC).filter(f => RASTER_EXTS.has(extname(f).toLowerCase())).sort()
  : [];

let rasterItems = [];

if (rasterSrcFiles.length > 0) {
  // Import sharp lazily so the SVG lane still works if sharp is not installed.
  let sharp;
  try {
    ({ default: sharp } = await import('sharp'));
  } catch {
    process.stderr.write(
      'illustrations:build — sharp not installed; skipping raster lane.\n' +
      '  Run: npm install --save-dev --workspace @kijani/illustrations sharp\n'
    );
  }

  if (sharp) {
    for (const f of rasterSrcFiles) {
      const name  = basename(f, extname(f));
      const title = kebabToTitle(name);
      const src   = join(RASTER_SRC, f);
      const meta  = await sharp(src).metadata();
      const srcW  = meta.width;
      const srcH  = meta.height;

      // 2x = original size → WebP
      const out2x = join(RASTER_OUT, `${name}@2x.webp`);
      await sharp(src).webp({ quality: 85 }).toFile(out2x);

      // 1x = 50% size → WebP  (round to even dimensions)
      const w1x = Math.max(1, Math.round(srcW / 2));
      const h1x = Math.max(1, Math.round(srcH / 2));
      const out1x = join(RASTER_OUT, `${name}.webp`);
      await sharp(src).resize(w1x, h1x).webp({ quality: 85 }).toFile(out1x);

      // Relative paths from src/web/ or src/native/ to raster/
      const relSrc   = `../../raster/${name}.webp`;
      const relSrc2x = `../../raster/${name}@2x.webp`;
      const aspectStr = `${w1x}/${h1x}`;

      rasterItems.push({ name, title, w1x, h1x, srcW, srcH, aspectStr, relSrc, relSrc2x, type: 'raster' });

      console.log(`  raster: ${name} → ${w1x}×${h1x} + ${srcW}×${srcH} (2x)`);

      // Web raster component
      const webSrc = `${HEADER}import * as React from 'react';

// Resolved by the consuming app's bundler (webpack / Vite / Metro).
// Add \`declare module '*.webp' { const src: string; export default src; }\`
// to your tsconfig if you see a TypeScript module-not-found error.
// eslint-disable-next-line @typescript-eslint/no-require-imports
const _src   = require('${relSrc}') as string;
// eslint-disable-next-line @typescript-eslint/no-require-imports
const _src2x = require('${relSrc2x}') as string;

export interface ${title}Props {
  /** Rendered width. Height auto-calculated (intrinsic ${w1x}∶${h1x}). */
  width?: number | string;
  alt?: string;
  className?: string;
  style?: React.CSSProperties;
}

export function ${title}({ width = ${w1x}, alt = '', className, style }: ${title}Props) {
  return (
    <img
      src={_src}
      srcSet={\`\${_src} 1x, \${_src2x} 2x\`}
      width={width}
      height={Math.round(Number(width) * ${h1x} / ${w1x})}
      alt={alt}
      className={className}
      style={{ aspectRatio: '${aspectStr}', ...style }}
    />
  );
}
`;
      writeFileSync(join(WEB_DIR, `${title}.tsx`), webSrc);

      // Native raster component (Metro @2x naming: require the 1x path; Metro
      // auto-resolves the @2x file on hi-DPI screens within the resolved package tree)
      const natSrc = `${HEADER}import * as React from 'react';
import { Image } from 'react-native';

// eslint-disable-next-line @typescript-eslint/no-require-imports
const _source = require('${relSrc}') as number;

export interface ${title}Props {
  /** Rendered width in dp. Height auto-calculated (intrinsic ${w1x}∶${h1x}). */
  width?: number;
  accessibilityLabel?: string;
}

export function ${title}({ width = ${w1x}, accessibilityLabel }: ${title}Props) {
  const height = Math.round(width * ${h1x} / ${w1x});
  return (
    <Image
      source={_source}
      style={{ width, height }}
      accessible={!!accessibilityLabel}
      accessibilityLabel={accessibilityLabel}
      resizeMode="contain"
    />
  );
}
`;
      writeFileSync(join(NAT_DIR, `${title}.tsx`), natSrc);
    }
  }
}

/* ── Manifest ── */

const allItems = [...svgItems, ...rasterItems];

const manifestLines = allItems.map(item => {
  if (item.type === 'svg') {
    return `  '${item.name}': { type: 'svg',    width: ${item.vbW}, height: ${item.vbH} },`;
  }
  return `  '${item.name}': { type: 'raster', width: ${item.w1x}, height: ${item.h1x}, src: '${item.relSrc}', src2x: '${item.relSrc2x}' },`;
}).join('\n');

const manifestSrc = `${HEADER}export type IllustrationMeta =
  | { type: 'svg';    width: number; height: number; alt?: string }
  | { type: 'raster'; width: number; height: number; src: string; src2x: string; alt?: string };

export const manifest: Readonly<Record<string, IllustrationMeta>> = {
${manifestLines}
} as const;

export type IllustrationName = keyof typeof manifest;
`;
writeFileSync(join(__dirname, 'manifest.ts'), manifestSrc);

/* ── Unified Illustration components ── */

const importLines    = allItems.map(i => `import { ${i.title} } from './${i.title}';`).join('\n');
const regLines       = allItems.map(i => `  '${i.name}': ${i.title},`).join('\n');
const typeNames      = allItems.map(i => `'${i.name}'`).join(' | ');
const defaultWidth   = allItems[0]?.vbW ?? allItems[0]?.w1x ?? 240;

const unifiedWeb = `${HEADER}import * as React from 'react';
${importLines}
import type { IllustrationMeta } from '../../manifest';

type IllustrationName = ${typeNames || 'never'};

const REGISTRY: Record<string, React.ComponentType<{ width?: number | string; alt?: string; className?: string; style?: React.CSSProperties }>> = {
${regLines}
};

export interface IllustrationProps {
  /** Illustration identifier. */
  name: IllustrationName;
  /** Width override. Defaults to the intrinsic 1× width. */
  width?: number | string;
  /** Accessible label. Omit for decorative illustrations. */
  alt?: string;
  className?: string;
  style?: React.CSSProperties;
}

export function Illustration({ name, width, alt, className, style }: IllustrationProps) {
  const Component = REGISTRY[name];
  if (!Component) {
    if (process.env.NODE_ENV !== 'production') {
      // eslint-disable-next-line no-console
      console.warn('[Illustration] Unknown name:', name);
    }
    return null;
  }
  return <Component width={width} alt={alt} className={className} style={style} />;
}
`;
writeFileSync(join(WEB_DIR, 'Illustration.tsx'), unifiedWeb);

const unifiedNat = `${HEADER}import * as React from 'react';
${allItems.map(i => `import { ${i.title} } from './${i.title}';`).join('\n')}

type IllustrationName = ${typeNames || 'never'};

const REGISTRY: Record<string, React.ComponentType<{ width?: number; accessibilityLabel?: string }>> = {
${regLines}
};

export interface IllustrationProps {
  name: IllustrationName;
  width?: number;
  accessibilityLabel?: string;
}

export function Illustration({ name, width, accessibilityLabel }: IllustrationProps) {
  const Component = REGISTRY[name];
  if (!Component) return null;
  return <Component width={width} accessibilityLabel={accessibilityLabel} />;
}
`;
writeFileSync(join(NAT_DIR, 'Illustration.tsx'), unifiedNat);

/* ── Barrels ── */

const barrelExports = [
  ...allItems.map(i => `export { ${i.title} } from './${i.title}';\nexport type { ${i.title}Props } from './${i.title}';`),
  `export { Illustration } from './Illustration';`,
  `export type { IllustrationProps } from './Illustration';`,
].join('\n');

writeFileSync(join(WEB_DIR, 'index.ts'),
  HEADER + barrelExports + '\n');

writeFileSync(join(NAT_DIR, 'index.ts'),
  HEADER + barrelExports + '\n');

/* ── Root entry points ── */

writeFileSync(join(__dirname, 'index.ts'),
  HEADER + `export * from './src/web/index';\nexport type { IllustrationName, IllustrationMeta } from './manifest';\n`);

writeFileSync(join(__dirname, 'native.ts'),
  HEADER + `export * from './src/native/index';\nexport type { IllustrationName, IllustrationMeta } from './manifest';\n`);

/* ── Summary ── */
const svgCount    = svgItems.length;
const rasterCount = rasterItems.length;
console.log(`✓ illustrations built (${svgCount} vector + ${rasterCount} raster)`);
console.log(`  src/web/    → ${allItems.map(i => i.title + '.tsx').join(', ')}, Illustration.tsx`);
console.log(`  src/native/ → ${allItems.map(i => i.title + '.tsx').join(', ')}, Illustration.tsx`);
console.log(`  manifest.ts · index.ts · native.ts`);
if (rasterCount > 0) {
  console.log(`  raster/     → ${rasterItems.map(i => `${i.name}.webp + ${i.name}@2x.webp`).join(', ')}`);
}
