// AUTO-GENERATED by packages/illustrations/build.mjs — DO NOT EDIT BY HAND.
// Source: packages/illustrations/svg/ or raster-src/. Run `npm run illustrations:build`.

export * from './src/web/index';
export type { IllustrationName, IllustrationMeta } from './manifest';
