// AUTO-GENERATED by packages/illustrations/build.mjs — DO NOT EDIT BY HAND.
// Source: packages/illustrations/svg/ or raster-src/. Run `npm run illustrations:build`.

export type IllustrationMeta =
  | { type: 'svg';    width: number; height: number; alt?: string }
  | { type: 'raster'; width: number; height: number; src: string; src2x: string; alt?: string };

export const manifest: Readonly<Record<string, IllustrationMeta>> = {
  'coin': { type: 'svg',    width: 240, height: 180 },
  'battery': { type: 'raster', width: 188, height: 98, src: '../../raster/battery.webp', src2x: '../../raster/battery@2x.webp' },
  'error': { type: 'raster', width: 54, height: 54, src: '../../raster/error.webp', src2x: '../../raster/error@2x.webp' },
} as const;

export type IllustrationName = keyof typeof manifest;
