// AUTO-GENERATED by packages/illustrations/build.mjs — DO NOT EDIT BY HAND.
// Source: packages/illustrations/svg/ or raster-src/. Run `npm run illustrations:build`.

export type IllustrationMeta =
  | { type: 'svg';    width: number; height: number; alt?: string }
  | { type: 'raster'; width: number; height: number; src: string; src2x: string; alt?: string };

export const manifest: Readonly<Record<string, IllustrationMeta>> = {
  'empty-state': { type: 'svg',    width: 240, height: 180 },
  'hero-banner': { type: 'raster', width: 200, height: 150, src: '../../raster/hero-banner.webp', src2x: '../../raster/hero-banner@2x.webp' },
} as const;

export type IllustrationName = keyof typeof manifest;
