#!/usr/bin/env node
/**
 * Token transform — reads src/tokens/source/*.json (Tokens Studio shape),
 * resolves {…} references, emits:
 *   - src/tokens/primitives.css
 *   - src/tokens/semantics.css
 *   - src/tokens/component-tokens.css
 *   - src/tokens/tokens.ts
 *
 * Zero deps. Pure Node ESM. The source/ files are also what Tokens Studio
 * in Figma reads via GitHub sync.
 */

import { readFileSync, writeFileSync, readdirSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC = join(__dirname, "source");
const OUT = __dirname;

const HEADER = `/* AUTO-GENERATED by src/tokens/build.mjs — DO NOT EDIT BY HAND.
   Source: src/tokens/source/*.json. Run \`npm run tokens:build\`. */\n\n`;

/* ---------- helpers ---------- */

const readJSON = (p) => JSON.parse(readFileSync(p, "utf8"));

/** Walk a token tree; call fn(path, tokenNode) for every leaf with a $value. */
function walk(node, path = [], fn) {
  if (!node || typeof node !== "object") return;
  if ("$value" in node) {
    fn(path, node);
    return;
  }
  for (const [key, child] of Object.entries(node)) {
    if (key.startsWith("$")) continue;
    walk(child, [...path, key], fn);
  }
}

/** Path → CSS variable name: ["color","brand","700"] → "--color-brand-700" */
const cssVar = (path) => `--${path.join("-")}`;

/** Resolve every {ref} in `value` to either a literal or a var(--…) ref. */
function resolveRefs(value, lookup, mode = "literal") {
  if (typeof value !== "string") return value;
  return value.replace(/\{([^}]+)\}/g, (_, ref) => {
    const path = ref.split(".");
    if (mode === "css-var") return `var(${cssVar(path)})`;
    const node = lookup.get(ref);
    if (!node) throw new Error(`Unresolved token reference: {${ref}}`);
    return resolveRefs(formatValue(node), lookup, "literal");
  });
}

/** Format a token's $value into its CSS string form.
 *  If the token has `$extensions["design-system.css-value"]`, that wins for CSS
 *  output — used to ship clamp()/calc() expressions while keeping `$value`
 *  Figma-friendly. Pass `cssOnly=false` (the default for tokens.ts) to ignore
 *  the override and use the raw `$value`. */
function formatValue(node, cssOnly = false) {
  const cssOverride = node.$extensions?.["design-system.css-value"];
  if (cssOnly && typeof cssOverride === "string") return cssOverride;

  const v = node.$value;
  const t = node.$type;

  if (t === "boxShadow") {
    if (Array.isArray(v)) {
      return v.map(formatShadowPart).join(", ");
    }
    if (typeof v === "object") return formatShadowPart(v);
    return String(v);
  }

  return String(v);
}

function formatShadowPart(s) {
  if (typeof s === "string") return s;
  const inset = s.type === "innerShadow" ? "inset " : "";
  return `${inset}${s.x} ${s.y} ${s.blur} ${s.spread || "0"} ${s.color}`.trim();
}

/** Deep-merge two token trees (later wins, leaf-by-leaf). */
function merge(a, b) {
  if (a == null) return b;
  if (b == null) return a;
  if (typeof a !== "object" || typeof b !== "object") return b;
  if ("$value" in a || "$value" in b) return b;
  const out = { ...a };
  for (const [k, v] of Object.entries(b)) {
    out[k] = merge(a[k], v);
  }
  return out;
}

/* ---------- load all source sets ---------- */

const sets = {};
for (const file of readdirSync(SRC)) {
  if (!file.endsWith(".json") || file.startsWith("$")) continue;
  const name = file.replace(/\.json$/, "");
  sets[name] = readJSON(join(SRC, file));
}

/* ---------- compose modes ---------- */

const baseCore = sets["core"];
const compactComponentsLight = sets["components"];
const compactComponentsDark  = merge(sets["components"], sets["components-dark"] || {});

const lightTree   = merge(baseCore, merge(sets["color-light"], compactComponentsLight));
const darkTree    = merge(baseCore, merge(sets["color-dark"],  compactComponentsDark));

/* ---------- build flat lookups for ref resolution ---------- */

function flatten(tree) {
  const map = new Map();
  walk(tree, [], (path, node) => map.set(path.join("."), node));
  return map;
}

const lightLookup = flatten(lightTree);
const darkLookup  = flatten(darkTree);

/* ---------- emit primitives.css ---------- */

function emitPrimitivesCSS() {
  const sections = [
    ["Color", ["color"]],
    ["Spacing", ["space"]],
    ["Typography — primitives", ["font-family", "font-size", "line-height", "letter-spacing", "font-weight"]],
    ["Radius", ["radius"]],
    ["Border width", ["border-width"]],
    ["Shadow", ["shadow"]],
    ["Opacity", ["opacity"]],
    ["Motion", ["duration", "ease"]],
    ["Z-index", ["z"]],
    ["Breakpoint", ["breakpoint"]],
  ];

  // Only primitives — values are literal, no refs.
  const primitiveOnly = {};
  for (const [, prefixes] of sections) {
    for (const p of prefixes) {
      if (baseCore[p]) primitiveOnly[p] = baseCore[p];
    }
  }
  // Filter color to only the scales (drop semantic.color sub-trees).
  if (primitiveOnly.color) {
    primitiveOnly.color = Object.fromEntries(
      Object.entries(primitiveOnly.color).filter(([k]) =>
        ["neutral", "brand", "info", "success", "warning", "danger", "white", "black", "transparent"].includes(k)
      )
    );
  }

  let out = HEADER + ":root {\n";
  for (const [title, prefixes] of sections) {
    out += `  /* ---------- ${title} ---------- */\n`;
    for (const p of prefixes) {
      if (!primitiveOnly[p]) continue;
      walk(primitiveOnly[p], [p], (path, node) => {
        const value = formatValue(node, true);
        out += `  ${cssVar(path)}: ${value};\n`;
      });
      out += `\n`;
    }
  }
  out += "}\n\n";

  // prefers-reduced-motion override
  out += `@media (prefers-reduced-motion: reduce) {\n`;
  out += `  :root {\n`;
  for (const k of ["instant", "fast", "base", "slow", "slower"]) {
    out += `    --duration-${k}: 0ms;\n`;
  }
  out += `  }\n}\n`;

  writeFileSync(join(OUT, "primitives.css"), out);
}

/* ---------- emit semantics.css ---------- */

function emitSemanticsCSS() {
  let out = HEADER;

  const writeBlock = (selector, tree, includeColor) => {
    let block = `${selector} {\n`;
    // Mode-agnostic semantics live in core; mode-specific in color-{light,dark}.
    // For the light :root block, write everything (mode-agnostic + light colors).
    // For [data-theme="dark"], write only the color overrides.
    if (includeColor) {
      walk(tree.color || {}, ["color"], (path, node) => {
        // Skip primitive color scales (those live in primitives.css).
        const family = path[1];
        if (["neutral", "brand", "info", "success", "warning", "danger", "white", "black", "transparent"].includes(family)) return;
        block += `  ${cssVar(path)}: ${resolveRefs(formatValue(node, true), null, "css-var")};\n`;
      });
    }
    if (selector === ":root") {
      // Mode-agnostic semantic groups
      for (const group of ["elevation", "text", "space-inset", "space-stack", "space-inline"]) {
        if (!baseCore[group]) continue;
        block += `\n  /* ${group} */\n`;
        walk(baseCore[group], [group], (path, node) => {
          block += `  ${cssVar(path)}: ${resolveRefs(formatValue(node, true), null, "css-var")};\n`;
        });
      }
    }
    block += `}\n\n`;
    return block;
  };

  out += writeBlock(":root", lightTree, true);
  out += writeBlock('[data-theme="dark"]', darkTree, true);

  writeFileSync(join(OUT, "semantics.css"), out);
}

/* ---------- emit component-tokens.css ---------- */

function emitComponentsCSS() {
  let out = HEADER;

  const writeBlock = (selector, componentTree) => {
    let block = `${selector} {\n`;
    for (const [comp, tree] of Object.entries(componentTree)) {
      block += `  /* ---------- ${comp} ---------- */\n`;
      walk(tree, [comp], (path, node) => {
        block += `  ${cssVar(path)}: ${resolveRefs(formatValue(node, true), null, "css-var")};\n`;
      });
      block += `\n`;
    }
    block += `}\n\n`;
    return block;
  };

  out += writeBlock(":root", compactComponentsLight);

  // Dark-mode component overrides (diff vs. compact light).
  const darkDiff = diffTokens(compactComponentsLight, compactComponentsDark);
  if (Object.keys(darkDiff).length > 0) {
    out += writeOverrideBlock('[data-theme="dark"]', darkDiff);
  }

  writeFileSync(join(OUT, "component-tokens.css"), out);
}

function writeOverrideBlock(selector, diff) {
  let block = `${selector} {\n`;
  for (const [comp, tree] of Object.entries(diff)) {
    block += `  /* ${comp} */\n`;
    walk(tree, [comp], (path, node) => {
      block += `  ${cssVar(path)}: ${resolveRefs(formatValue(node, true), null, "css-var")};\n`;
    });
  }
  block += `}\n\n`;
  return block;
}

/** Return a sub-tree of `b` containing only leaves whose $value differs from `a`. */
function diffTokens(a, b) {
  const out = {};
  walk(b, [], (path, node) => {
    let cursor = a;
    for (const seg of path) {
      cursor = cursor?.[seg];
      if (!cursor) break;
    }
    if (!cursor || JSON.stringify(cursor.$value) !== JSON.stringify(node.$value)) {
      let target = out;
      for (let i = 0; i < path.length - 1; i++) {
        target[path[i]] ??= {};
        target = target[path[i]];
      }
      target[path[path.length - 1]] = node;
    }
  });
  return out;
}

/* ---------- emit tokens.ts ---------- */

function emitTokensTS() {
  const buildFlat = (lookup) => {
    const flat = {};
    for (const [path, node] of lookup.entries()) {
      flat[`--${path.split(".").join("-")}`] = resolveRefs(formatValue(node), lookup, "literal");
    }
    return flat;
  };

  const light = buildFlat(flatten(lightTree));
  const dark  = buildFlat(flatten(darkTree));

  const json = (obj) => JSON.stringify(obj, null, 2);

  const out = `// AUTO-GENERATED by src/tokens/build.mjs — DO NOT EDIT BY HAND.
// Flat token maps for non-CSS consumers (React Native, JS-only tooling).
// Each map resolves all {…} refs to literal values for the given theme.

export type ThemeMode = "light" | "dark";

export type TokenName = keyof typeof tokens.light;

export const tokens = {
  light: ${json(light)} as const,
  dark: ${json(dark)} as const,
} as const;

/** Resolve a token name against the active theme. */
export function resolveToken(
  name: TokenName,
  theme: ThemeMode = "light",
): string {
  return tokens[theme][name];
}
`;
  writeFileSync(join(OUT, "tokens.ts"), out);
}

/* ---------- emit tokens.figma-variables.json ---------- */

/** Map our $type values to Figma's Variable resolvedType. Composite types
 *  (boxShadow, typography) and CSS-only types (durations, easings, z-index)
 *  return null and are skipped — they can't be represented as Figma Variables. */
function figmaType(t) {
  switch (t) {
    case "color": return "COLOR";
    case "dimension":
    case "spacing":
    case "sizing":
    case "borderRadius":
    case "borderWidth":
    case "fontSizes":
    case "lineHeights":
    case "opacity":
      return "FLOAT";
    case "fontWeights":
      // Figma's text.fontStyle is a string ("Medium", "Bold"). Numeric weights
      // can't be bound directly; the figma-value override translates 500→"Medium".
      return "STRING";
    case "fontFamilies":
    case "letterSpacing":
      return "STRING";
    default:
      return null;
  }
}

/** Format a token node's value for Figma Variables.
 *  Returns { alias: "path/to/var" } for references, { value: <literal> } otherwise,
 *  or null if the value can't be represented (compound spacing, etc).
 *
 *  If a node has `$extensions["design-system.figma-value"]`, that value is used
 *  for Figma output regardless of `$value`. This lets us keep CSS-friendly
 *  values (e.g. font-family stacks, numeric font-weight) in `$value` while
 *  giving Figma the strings it actually needs (e.g. "Inter", "Medium"). */
function figmaValueFor(node, type) {
  // Figma-specific override takes precedence. Only applies to literals — aliases
  // are inferred from $value structure either way.
  const override = node.$extensions && node.$extensions["design-system.figma-value"];
  if (override !== undefined) {
    if (type === "COLOR") return { value: String(override) };
    if (type === "FLOAT") {
      const n = typeof override === "number" ? override : parseFloat(override);
      return Number.isFinite(n) ? { value: n } : null;
    }
    if (type === "STRING") return { value: String(override) };
    return null;
  }

  const v = node.$value;

  if (typeof v === "string") {
    const refMatch = v.match(/^\{([^}]+)\}$/);
    if (refMatch) {
      return { alias: refMatch[1].replace(/\./g, "/") };
    }
  }

  if (type === "COLOR") {
    return { value: String(v) };
  }
  if (type === "FLOAT") {
    const str = String(v).trim();
    if (/\s/.test(str)) return null;
    const n = parseFloat(str);
    return Number.isFinite(n) ? { value: n } : null;
  }
  if (type === "STRING") {
    return { value: String(v) };
  }
  return null;
}

function emitFigmaVariablesJSON() {
  const modes = [
    { id: "light", name: "Light", tree: lightTree },
    { id: "dark",  name: "Dark",  tree: darkTree },
  ].map((m) => ({ ...m, lookup: flatten(m.tree) }));

  // Union of every token path across every mode.
  const allPaths = new Set();
  for (const m of modes) for (const p of m.lookup.keys()) allPaths.add(p);

  const variables = [];
  for (const path of [...allPaths].sort()) {
    // Type comes from the first mode that has the node — types are consistent
    // across modes for a given token.
    let firstNode = null;
    for (const m of modes) {
      if (m.lookup.has(path)) { firstNode = m.lookup.get(path); break; }
    }
    if (!firstNode) continue;

    const type = figmaType(firstNode.$type);
    if (!type) continue;

    const valuesByMode = {};
    for (const m of modes) {
      const n = m.lookup.get(path);
      if (!n) continue;
      const val = figmaValueFor(n, type);
      if (val) valuesByMode[m.id] = val;
    }
    if (Object.keys(valuesByMode).length === 0) continue;

    variables.push({
      name: path.replace(/\./g, "/"),
      type,
      values: valuesByMode,
    });
  }

  const out = {
    $schema: "design-system.figma-variables.v1",
    collectionName: "Design System",
    modes: modes.map(({ id, name }) => ({ id, name })),
    variables,
  };

  writeFileSync(join(OUT, "tokens.figma-variables.json"), JSON.stringify(out, null, 2));
}

/* ---------- run ---------- */

emitPrimitivesCSS();
emitSemanticsCSS();
emitComponentsCSS();
emitTokensTS();
emitFigmaVariablesJSON();

console.log("✓ tokens built:");
console.log("  - src/tokens/primitives.css");
console.log("  - src/tokens/semantics.css");
console.log("  - src/tokens/component-tokens.css");
console.log("  - src/tokens/tokens.ts");
console.log("  - src/tokens/tokens.figma-variables.json");
