#!/usr/bin/env node
// AUTO-generates per-icon React (web) + react-native-svg (native) components
// from SVG sources in packages/icons/svg/.
//
// Output:
//   src/web/<Name>.tsx        forwardRef components (SVGProps extension)
//   src/native/<Name>.tsx     react-native-svg components
//   src/web/index.ts          web barrel + IconName type
//   src/native/index.ts       native barrel + IconName type
//   index.ts                  root web re-export
//   native.ts                 root native re-export
//
// Zero runtime dependencies — pure Node ESM. Run: node packages/icons/build.mjs

import { readFileSync, writeFileSync, readdirSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SVG_DIR  = join(__dirname, 'svg');
const WEB_DIR  = join(__dirname, 'src', 'web');
const NAT_DIR  = join(__dirname, 'src', 'native');

mkdirSync(WEB_DIR, { recursive: true });
mkdirSync(NAT_DIR, { recursive: true });

const HEADER = `// AUTO-GENERATED by packages/icons/build.mjs — DO NOT EDIT BY HAND.
// Source: packages/icons/svg/. Run \`npm run icons:build\` to regenerate.

`;

// SVG kebab-case attribute → JSX camelCase
const ATTR_MAP = {
  'stroke-width':      'strokeWidth',
  'stroke-linecap':    'strokeLinecap',
  'stroke-linejoin':   'strokeLinejoin',
  'stroke-dasharray':  'strokeDasharray',
  'stroke-dashoffset': 'strokeDashoffset',
  'fill-rule':         'fillRule',
  'clip-rule':         'clipRule',
  'clip-path':         'clipPath',
};

// SVG element name → react-native-svg component name
// Longer names first to avoid partial matches (e.g. 'line' inside 'linearGradient')
const NATIVE_ELEMS = [
  ['linearGradient', 'LinearGradient'],
  ['radialGradient', 'RadialGradient'],
  ['clipPath',       'ClipPath'],
  ['ellipse',        'Ellipse'],
  ['polygon',        'Polygon'],
  ['polyline',       'Polyline'],
  ['circle',         'Circle'],
  ['defs',           'Defs'],
  ['path',           'Path'],
  ['rect',           'Rect'],
  ['stop',           'Stop'],
  ['text',           'Text'],
  ['use',            'Use'],
  ['line',           'Line'],
  ['g',              'G'],
];

/** "arrow-left" → "ArrowLeft" */
function kebabToTitle(s) {
  return s.split('-').map(w => w[0].toUpperCase() + w.slice(1)).join('');
}

/** Extract inner SVG content, normalising indentation to zero. */
function svgInner(raw) {
  const m = raw.match(/<svg[^>]*>([\s\S]*?)<\/svg>/);
  if (!m) return '';
  const lines = m[1].split('\n').filter(l => l.trim());
  const minIndent = Math.min(...lines.map(l => l.match(/^(\s*)/)[1].length));
  return lines.map(l => l.slice(minIndent)).join('\n').trim();
}

/** Rename SVG attributes to JSX camelCase and bind "currentColor" to {color}. */
function toJSX(content) {
  let s = content;
  for (const [from, to] of Object.entries(ATTR_MAP)) {
    s = s.replace(new RegExp(from + '=', 'g'), to + '=');
  }
  return s.replace(/"currentColor"/g, '{color}');
}

/** Map SVG element names to react-native-svg component names. */
function toNativeElems(content) {
  let s = content;
  for (const [from, to] of NATIVE_ELEMS) {
    const esc = from.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    s = s.replace(new RegExp('<' + esc + '([\\s/>])', 'g'), '<' + to + '$1');
    s = s.replace(new RegExp('<\\/' + esc + '>', 'g'), '</' + to + '>');
  }
  return s;
}

/** Return sorted list of react-native-svg components used in the native inner content. */
function detectNativeImports(nativeContent) {
  const used = new Set();
  for (const [, to] of NATIVE_ELEMS) {
    if (new RegExp('<' + to + '[\\s/>]').test(nativeContent)) used.add(to);
  }
  return [...used].sort();
}

/** Indent every non-empty line by n spaces. */
function indent(str, n) {
  const pad = ' '.repeat(n);
  return str.split('\n').map(l => (l.trim() ? pad + l : '')).join('\n');
}

// ── Parse all SVG sources ────────────────────────────────────────────────────

const icons = readdirSync(SVG_DIR)
  .filter(f => f.endsWith('.svg'))
  .sort()
  .map(f => {
    const name    = f.replace('.svg', '');
    const title   = kebabToTitle(name);
    const raw     = readFileSync(join(SVG_DIR, f), 'utf8');
    const inner   = svgInner(raw);
    const jsxBody = toJSX(inner);
    const natBody = toNativeElems(jsxBody);
    return { name, title, jsxBody, natBody };
  });

// ── Web components ───────────────────────────────────────────────────────────

for (const { title, jsxBody } of icons) {
  const src = `${HEADER}import * as React from 'react';

export interface ${title}Props extends React.SVGProps<SVGSVGElement> {
  size?: number | string;
  color?: string;
}

export const ${title} = React.forwardRef<SVGSVGElement, ${title}Props>(
  function ${title}({ size = 24, color = 'currentColor', ...rest }, ref) {
    return (
      <svg
        ref={ref}
        xmlns="http://www.w3.org/2000/svg"
        width={size}
        height={size}
        viewBox="0 0 24 24"
        fill="none"
        aria-hidden="true"
        {...rest}
      >
${indent(jsxBody, 8)}
      </svg>
    );
  }
);

${title}.displayName = '${title}';
`;
  writeFileSync(join(WEB_DIR, title + '.tsx'), src);
}

// ── Native components ────────────────────────────────────────────────────────

for (const { title, natBody } of icons) {
  const imports = detectNativeImports(natBody);
  const src = `${HEADER}import * as React from 'react';
import Svg, { ${imports.join(', ')} } from 'react-native-svg';

export interface ${title}Props {
  size?: number;
  color?: string;
}

export function ${title}({ size = 24, color = 'currentColor' }: ${title}Props) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none">
${indent(natBody, 6)}
    </Svg>
  );
}
`;
  writeFileSync(join(NAT_DIR, title + '.tsx'), src);
}

// ── Barrel files ─────────────────────────────────────────────────────────────

const iconNames = icons.map(i => `'${i.name}'`).join(' | ');

const webBarrel = HEADER
  + icons.map(i =>
    `export { ${i.title} } from './${i.title}';\nexport type { ${i.title}Props } from './${i.title}';`
  ).join('\n')
  + `\n\nexport type IconName = ${iconNames};\n`;
writeFileSync(join(WEB_DIR, 'index.ts'), webBarrel);

const natBarrel = HEADER
  + icons.map(i =>
    `export { ${i.title} } from './${i.title}';\nexport type { ${i.title}Props } from './${i.title}';`
  ).join('\n')
  + `\n\nexport type IconName = ${iconNames};\n`;
writeFileSync(join(NAT_DIR, 'index.ts'), natBarrel);

// ── Root entry points ────────────────────────────────────────────────────────

writeFileSync(join(__dirname, 'index.ts'),
  HEADER + `export * from './src/web/index';\n`);

writeFileSync(join(__dirname, 'native.ts'),
  HEADER + `export * from './src/native/index';\n`);

console.log(`✓ icons built (${icons.length} icons)`);
console.log(`  src/web/   → ${icons.map(i => i.title + '.tsx').join(', ')}, index.ts`);
console.log(`  src/native/ → ${icons.map(i => i.title + '.tsx').join(', ')}, index.ts`);
console.log(`  index.ts (web), native.ts (RN)`);
